########################################################
## CONFIG
########################################################
timer:
  flood_sensor_kitchen:
    duration: '00:00:10'

########################################################
## AUTOMATIONS
########################################################
automation:
###################
## start timer
##
  - alias: Kitchen flood sensor timer start
    trigger:
      platform: state
      entity_id: binary_sensor.water_leak_sensor_158d0002879b30
      to: 'on'
    action:
    - service: timer.start
      data:
        duration: 00:00:10
        entity_id: timer.flood_sensor_kitchen
###################
## warn after timer
##
  - alias: Kitchen flood warning
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.flood_sensor_kitchen
    condition:
      condition: state
      entity_id: binary_sensor.water_leak_sensor_158d0002879b30
      state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.house_announce_echos
        data_template:
          tts_msg: "I am detecting a water leak under the dishwasher."
      - service: notify.pushover_timhiphonex
        data_template:
          message: "I am detecting a water leak under the dishwasher."
      - service: timer.start
        data:
          duration: 00:00:10
          entity_id: timer.flood_sensor_kitchen
