########################################################
## CONFIG
########################################################
timer:
  freezer_door:
    duration: '00:00:30'

########################################################
## AUTOMATIONS
########################################################
automation:
###################
## alert starts
##
  - alias: Fridge door warning
    trigger:
      platform: state
      entity_id: alert.fridge_door
      to: 'on'
    action:
      - service: timer.start
        data:
          duration: 00:01:15
          entity_id: timer.fridge_door
###################
## alert repeat
##
  - alias: Fridge door warning repeat
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.fridge_door
    condition:
      condition: state
      entity_id: alert.fridge_door
      state: 'on'
    action:
      - service: script.house_announce_downstairs
        data_template:
          tts_msg: >
              '{{ [
              "Warning, the fridge door is still open. " ,
              "The fridge door is <emphasis level='strong'>still</emphasis> open. " ,
              "I think the fridge door is still open. " ,
              "It looks like the fridge door is still open. " ,
              "I think the fridge door is still open. " ,
              "Warning, I think the fridge door is still open. " 
              ] |random }}'
      - service: timer.start
        data:
          duration: 00:01:00
          entity_id: timer.fridge_door
###################
## alert ends
##
  - alias: Fridge door warning finished
    trigger:
      platform: state
      entity_id: alert.fridge_door
      to: 'idle'
    condition:
      condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.alert.fridge_door.last_updated) > 60 }}'
    action:
      - service: timer.cancel
        data:
          entity_id: timer.fridge_door
      - service: script.house_announce_downstairs
        data_template:
          tts_msg: "The fridge door is now closed."