########################################################
## CONFIG
########################################################
timer:
  left_shed_door:
    duration: '00:10:00'

########################################################
## AUTOMATIONS
########################################################
automation:
###################
## start timer
##
  - alias: Left shed door timer start
    trigger:
      platform: state
      entity_id: sensor.window_left_shed_door
      to: 'Open'
    action:
      - service: timer.start
        data:
          entity_id: timer.left_shed_door
###################
## warn after timer
##
  - alias: Left shed door warning
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.left_shed_door
    condition:
      condition: state
      entity_id: sensor.window_left_shed_door
      state: 'Open'
    action:
      - service: script.house_announce_downstairs
        data_template:
          notification_feed_name: LeftShedDoor
          tts_msg: "The left shed door is open."
      - service: timer.start
        data:
          entity_id: timer.left_shed_door