# - platform: climate_group
#   name: Office windows
#   # icon: mdi:window-open-variant
#   entities:
#   - binary_sensor.door_window_sensor_158d0002d462e6
#   - binary_sensor.door_window_sensor_158d0003c7a4bc

- platform: better_thermostat
  name: Porch
  thermostat: climate.trv_porch
  temperature_sensor: sensor.hasubsystem_ble_temperature_a4c13851ceff
  window_sensors: binary_sensor.door_window_sensor_158d00045c91f4 # group.office_windows # if this is not set, the window open detection is off
  # weather: weather.openweathermap # if this is set, the outdoor_sensor is ignored, remove the outdoor_sensor config!
  # outdoor_sensor: sensor.outdoor_temperature # if you want to use it, remove the weather entity from the config!
  off_temperature: 17.5
  # window_off_delay: 15 # in seconds
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Office
  thermostat: climate.trv_office
  temperature_sensor: sensor.hasubsystem_ble_temperature_a4c138f58611
  window_sensors: group.office_windows
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Dining room
  thermostat: climate.trv_dining_room
  temperature_sensor: sensor.hasubsystem_ble_temperature_a4c138721a4d
  window_sensors: binary_sensor.door_window_sensor_158d0002fd436f
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Living room
  thermostat: climate.trv_living_room
  temperature_sensor: sensor.hasubsystem_ble_temperature_a4c138a455e8
  window_sensors: binary_sensor.door_window_sensor_158d0002fd436f # dining room window
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Tim room
  thermostat: climate.trv_tim_room
  temperature_sensor: sensor.hasubsystem_ble_temperature_a4c138199270
  window_sensors: binary_sensor.door_window_sensor_158d0004096c56 # Jed window
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Fin room
  thermostat: climate.trv_fin_room
  temperature_sensor: sensor.hasubsystem_ble_temperature_a4c1382166dc
  window_sensors: binary_sensor.door_window_sensor_158d00047e651c
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Jed room
  thermostat: climate.trv_jed_room
  temperature_sensor: sensor.hasubsystem_ble_temperature_a4c13878b216
  window_sensors: binary_sensor.door_window_sensor_158d0004096c56 # Jed window
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Bathroom
  thermostat: climate.trv_bathroom
  temperature_sensor: sensor.hasubsystem_ble_temperature_582d3438aab9
  window_sensors: binary_sensor.door_window_sensor_158d0004096c56 # Jed window
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'
- platform: better_thermostat
  name: Landing
  thermostat: climate.trv_landing
  temperature_sensor: sensor.hue_landing_temperature
  window_sensors: binary_sensor.door_window_sensor_158d0004096c56 # Jed window
  off_temperature: 17.5
  valve_maintenance: true
  night_temp: 17.5
  night_start: '22:00'
  night_end: '06:00'