sensor:
  # Ron Swanson 
  - platform: rest
    name: Ron Swanson quote api
    resource: https://ron-swanson-quotes.herokuapp.com/v2/quotes
  - platform: template
      ron_swanson_quote:
        friendly_name: "Ron"
        # remove [" and "]
        value_template: "{{ states('sensor.ron_swanson_quote_api')|replace('[\"','')|replace('\"]','') }}"   
group:
  quotations:
    name: Random quotes
    view: false
    control: hidden
    entities:
      - sensor.ron_swanson_quote