###############################################
#  Homekit
###############################################
  - filter:
  #    include_domains:
  #    e.g. "Hey Siri, turn on Radio 4 [input_boolean]"
  #    e.g. "Hey Siri, Block Party louder"
  #      - input_boolean
  #    exclude_entities:
      include_entities:
        #  Lyric thermostat now configured via Homekit Controller
        # - climate.lyric
        #  Front door lock as fake Garage Door
        - cover.garage_door_front_door_lock
        # TRVs
        - climate.trv_tim_room
        - climate.trv_fin_room
        - climate.trv_fin_desk
        - climate.trv_jed_room
        - climate.trv_bathroom
        - climate.trv_landing
        - climate.trv_living_room
        - climate.trv_living_room_sofa
        - climate.trv_dining_room
        - climate.trv_office
        - climate.trv_porch
        # vacuum rooms
        - script.vacuum_house
        - script.vacuum_upstairs
        - script.vacuum_downstairs
        - script.vacuum_office
        - script.vacuum_living_room
        - script.vacuum_dining_room
        - script.vacuum_kitchen
        - script.vacuum_tims_room
        - script.vacuum_fins_room
        - script.vacuum_jeds_room
        - script.vacuum_landing
        # vacuum commands
        - script.vacuum_upstairs_pause
        - script.vacuum_upstairs_stop
        - script.vacuum_upstairs_cancel
        - script.vacuum_upstairs_dock
        - script.vacuum_upstairs_locate
        # - script.vacuum_upstairs_where
        # - script.vacuum_upstairs_resume
        - script.vacuum_upstairs_start
        - script.vacuum_downstairs_pause
        - script.vacuum_downstairs_stop
        - script.vacuum_downstairs_cancel
        - script.vacuum_downstairs_dock
        - script.vacuum_downstairs_locate
        # - script.vacuum_downstairs_where
        # - script.vacuum_downstairs_resume
        - script.vacuum_downstairs_start
        # 
        # lights
        # 
        #- light.gateway_light_04cf8c8fa2af # Xiaomi gateway
        #- light.bedside_lamp
        #- light.hue_color_candle_1 # dining room wall wash
        - switch.kitchen_spotlights
        - switch.kitchen_striplights
        - switch.wall_switch_158d000309dd3f # downstairs loo
  #      - switch.wall_switch_left_158d00030a7792
  #      - switch.wall_switch_right_158d00030a7792
  #      - switch.wall_switch_left_158d000406efb0
  #      - switch.wall_switch_right_158d000406efb0
        - script.tts_status_report
        # - script.amazon_music_ambient_piano_everywhere
        # - script.amazon_music_chamber_music_everywhere
        # - script.amazon_music_concertos_everywhere
        # - script.amazon_music_ballet_everywhere
        # - script.amazon_music_classical_everywhere
        # 
        # Scenes
        # 
        - script.lighting_scene_work_mode
        - script.lighting_scene_kids_mode
        - script.lighting_scene_rainbow_mode
        - script.lighting_scene_gaming_mode
        - script.lighting_scene_movie_mode
        - script.lighting_scene_normal_mode
        - script.lighting_scene_mealtime_mode
        - script.lighting_scene_prepare_for_bed
        - script.lighting_scene_going_upstairs
        - script.lighting_scene_good_night
        - script.lighting_scene_morning_routine
        # 
        # switches
        # 
        # - switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
        # - switch.smart_switch_1911296783282590805448e1e9121f70_outlet_3
        # - switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
        # - switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
        # replace with Input Booleans, these send power consumption data to Homekit every few seconds
        # - switch.zigbee_plug_8 # Fin fan
        # - switch.tuya_smart_plug_02 # Tim fan
        # - switch.zigbee_plug_2 # Jed fan
        # - switch.tuya_smart_plug_14 # Dragon plant
        # - switch.zigbee_plug_1 
        - switch.smart_plug_jed_fan
        - switch.smart_plug_tim_fan
        - switch.smart_plug_fin_fan
        - switch.smart_plug_dragon_plant
        - switch.test_energy_monitor 

        - input_boolean.random_light_living_room_floor
        - input_boolean.random_light_living_room_sofa
        - input_boolean.random_light_reading_light
        - input_boolean.random_light_dining_room_wall_wash
        - input_boolean.random_light_dining_room
        - input_boolean.random_light_tim_room
        - input_boolean.random_light_fin_room
        - input_boolean.random_light_jed_room

        - input_boolean.washingmachine_status_enquiry
        # - input_boolean.flashing_bedside_lamp
        - script.harmony_watch_youview
        - script.harmony_watch_apple_tv
        - script.harmony_play_ps4
        - script.harmony_play_xbox_x
        - script.harmony_watch_shield
        - script.harmony_play_ps5
        - script.harmony_play_nintendo_switch
        - script.harmony_power_off
        # 
        # House sounds
        # 
        #- switch.template_itunes_shuffle_status
        - switch.itunes_shuffle_switch
        - switch.switch_the_radio
        - switch.switch_the_music
        #- input_number.airplay_volume
        - media_player.itunes
        - input_boolean.increase_airplay_vol
        - input_boolean.decrease_airplay_vol
        - input_boolean.all_the_speakers
        - switch.switch_block_party
        - switch.switch_radio_1
        - switch.switch_radio_2
        - switch.switch_radio_3
        - switch.switch_radio_4
        - switch.switch_radio_5
        - switch.switch_talksport
        - switch.switch_oz_radio
        - switch.switch_jazz_radio
        - switch.switch_podcasts
        # 
        # Devices
        # 
        - switch.airplay_speakers_dining_room
        - switch.airplay_speakers_living_room
        - switch.airplay_speakers_kitchen
        - switch.airplay_speakers_office
        - switch.airplay_speakers_computer
        - switch.subwoofer_light_plug #subwoofer
        # - input_boolean.playstation_mode
        # - input_boolean.xbox_mode
        - switch.ps4
        - switch.xbox_x
        - switch.media_player_living_room_denon_avr
        - switch.media_player_sony_bravia_tv
        # - lock.conexis_l1 (moved to accessory mode)
        - binary_sensor.sliding_door_locked
        - alarm_control_panel.home_security
        # 
        # Location tracking
        # 
        - binary_sensor.presence_home_app_tim 
        # - binary_sensor.presence_shortcuts_app_tim
        - input_boolean.tim_present_home_app
        # - input_boolean.tim_present_shortcuts_app
        #
        # BELOW IS HOMEKIT ONLY, NOT ALEXA
        #
        #
        # Faster Hue motion sensors via Homekit
        #
        - input_boolean.hue_homekit_motion_office
        - input_boolean.hue_homekit_motion_stairs
        - input_boolean.hue_homekit_motion_landing
        - input_boolean.hue_homekit_motion_kitchen
        - input_boolean.hue_homekit_motion_office_keyboard
        #
        # motion sensors
        #
        - binary_sensor.zone_1_dining_room
        - binary_sensor.zone_2_living_room
        - binary_sensor.zone_3_landing
        - binary_sensor.motion_sensor_158d0002247bba
        - binary_sensor.motion_sensor_158d0003f131cf
        - binary_sensor.motion_sensor_158d0004239af0
        - binary_sensor.motion_sensor_158d00047b92a8
        - binary_sensor.motion_sensor_158d00047b936c 
        - binary_sensor.motion_sensor_158d000484379e
        - binary_sensor.rf_motion_sensor_1_downstairs_loo
        - binary_sensor.rf_motion_sensor_2_porch
        - binary_sensor.rf_motion_sensor_3_kitchen_oven
        - binary_sensor.rf_motion_sensor_4_kitchen_tv
        - binary_sensor.rf_motion_sensor_5_bathroom
        #
        - light.living_room_corner_accent_light # light.living_room_corner_accent_light is created by 'Switch as X' integration
        # Note, near the 150 device limit. Do NOT add any more, if exceeded it will break homekit room assignments
    entity_config:
      alarm_control_panel.home_security:
        code: !secret alarm_code
      script.amazon_music_ambient_piano_everywhere:
        name: Background piano
      media_player.itunes:
        name: Background music
        feature_list:
          - feature: play_pause
          - feature: toggle_mute
      media_player.living_room:
        feature_list:
          - feature: play_pause
      media_player.sony_bravia_tv:
        name: TV
        feature_list:
          - feature: on_off
          - feature: toggle_mute
      media_player.denon_avr_x3600h:
        feature_list:
          - feature: on_off
          - feature: toggle_mute
###############################################
#  2nd bridge
###############################################
  - name: Home Assistant 2 bridge
    port: 21064
    filter:
      include_entities:
        # Hue dimmer switches
        #
        - script.hue_scene_relax_living_room
        - script.hue_scene_read_living_room
        - script.hue_scene_colorloop_living_room
        - script.hue_scene_randomlight_living_room
        - script.hue_scene_off_living_room
        #
        - script.hue_scene_relax_dining_room
        - script.hue_scene_read_dining_room
        - script.hue_scene_colorloop_dining_room
        - script.hue_scene_randomlight_dining_room
        - script.hue_scene_off_dining_room
        #
        - script.hue_scene_relax_office
        - script.hue_scene_read_office
        - script.hue_scene_colorloop_office
        - script.hue_scene_randomlight_office
        - script.hue_scene_off_office
        #
        - script.hue_scene_relax_tim_room
        - script.hue_scene_read_tim_room
        - script.hue_scene_colorloop_tim_room
        - script.hue_scene_randomlight_tim_room
        - script.hue_scene_off_tim_room
        #
        - script.hue_scene_relax_fin_room
        - script.hue_scene_read_fin_room
        - script.hue_scene_colorloop_fin_room
        - script.hue_scene_randomlight_fin_room
        - script.hue_scene_off_fin_room
        #
        - script.hue_scene_relax_jed_room
        - script.hue_scene_read_jed_room
        - script.hue_scene_colorloop_jed_room
        - script.hue_scene_randomlight_jed_room
        - script.hue_scene_off_jed_room