title: Home Assistant phone mode
button_card_templates: !include lovelace/templates/button_card_templates.yaml
custom_header:
  compact_mode: true
  footer_mode: true
  indicator_top: true
  background: rgba(0,0,0,0.8)
  hide_unused: true
  hide_config: true
  hide_help: true
  chevrons: false
views:
#  - !include lovelace/views/view_old_home.yaml
#  - !include lovelace/views/view_old_info.yaml
#  - !include lovelace/views/view_old_server_info.yaml
#  - !include lovelace/views/view_old_charts.yaml
#  - !include lovelace/views/view_old_plants.yaml
#  - !include lovelace/views/view_old_media_players.yaml
#  - !include lovelace/views/view_old_data.yaml
#  - !include lovelace/views/view_okay.yaml
#  - !include lovelace/views/view_map.yaml
  - !include lovelace/views/view_phone_alarm.yaml
  - !include lovelace/views/view_phone_map.yaml
  - !include lovelace/views/view_phone_vacuum.yaml
  - !include lovelace/views/view_phone_house_info.yaml
  - !include lovelace/views/view_phone_network.yaml
  - !include lovelace/views/view_phone_thermostats.yaml
  - !include lovelace/views/view_phone_key_sensors.yaml
  - !include lovelace/views/view_phone_testing.yaml
  - !include lovelace/views/view_phone_network_new.yaml
  # - !include lovelace/views/view_favourites.yaml
  # - !include lovelace/views/view_network.yaml
  # - !include lovelace/views/view_info.yaml
  # - !include lovelace/views/view_testing.yaml
##########################################
##########################################
##########################################
##########################################
##########################################
##########################################
##########################################
##########################################
##########################################
##########################################
##########################################