  db_url: !secret mariadb_url
# Purge history older than X days
  purge_keep_days: 30
  exclude:
    domains:
      - climate
      - group
      # - media_player
      - sun
      - zone
      # - zwave
      # - light
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.solar_angle
      - sensor.sun_state
      - sensor.worldclock_sensor
      - sensor.chuck_norris_quote
      - sensor.ron_swanson_quote
      - sensor.ron_swanson_quote_api
      - script.bedtime_lights_delayed
      - script.bedtime_lights_delayed_test_2
# random lights
      - script.random_light_tim_room
      - script.random_light_tim_room_loop
      - script.random_light_fin_room
      - script.random_light_fin_room_loop
      - script.random_light_jed_room
      - script.random_light_jed_room_loop
      - script.random_light_living_room
      - script.random_light_living_room_loop
      - script.random_light_dining_room
      - script.random_light_dining_room_loop
      - script.random_light_dining_room_wall_wash
      - script.random_light_dining_room_wall_wash_loop
      - script.random_light_living_room_floor
      - script.random_light_living_room_floor_loop
      - script.random_light_living_room_sofa
      - script.random_light_living_room_sofa_loop
      - script.random_light_reading_light
      - script.random_light_reading_light_loop
      - automation.random_light_tim_room
      - automation.random_light_tim_room_loop
      - automation.random_light_fin_room
      - automation.random_light_fin_room_loop
      - automation.random_light_jed_room
      - automation.random_light_jed_room_loop
      - automation.random_light_living_room
      - automation.random_light_living_room_loop
      - automation.random_light_dining_room
      - automation.random_light_dining_room_off
      - automation.random_light_dining_room_wall_wash
      - automation.random_light_dining_room_wall_wash_loop
      - automation.random_light_living_room_floor
      - automation.random_light_living_room_floor_off
      - automation.random_light_living_room_sofa
      - automation.random_light_living_room_sofa_off
      - automation.random_light_reading_light
      - automation.random_light_reading_light_off
      # - input_boolean.random_light_tim_room
      # - input_boolean.random_light_fin_room
      # - input_boolean.random_light_jed_room
      # - input_boolean.random_light_living_room
      # - input_boolean.random_light_dining_room
      # - input_boolean.random_light_dining_room_wall_wash
      # - input_boolean.random_light_living_room_floor
      # - input_boolean.random_light_living_room_sofa
      # - input_boolean.random_light_reading_light
# device trackers
      - device_tracker.airport_extreme
      - device_tracker.amazon_8256dfa8e
      - device_tracker.amazon_8aca074c9
      - device_tracker.amazon_c62ce4b0b
      - device_tracker.amazon_echo_show
      - device_tracker.asus_n65u
      - device_tracker.washer_dryer_energy_monitor
#      - device_tracker.fin_iphone
#      - device_tracker.finiphone
#      - device_tracker.fins_iphone_6
      - device_tracker.garden_light_switch
      - device_tracker.google_home_mini
      - device_tracker.hassio
      - device_tracker.hd_homerun
#      - device_tracker.honor_6c
      - device_tracker.i7_27_imac
      - device_tracker.kitchen_airport_express
      - device_tracker.living_room
      - device_tracker.living_room_airport_express
      - device_tracker.lyric_ea5730
      - device_tracker.mac_mini
      - device_tracker.nintendo_switch
      - device_tracker.office_airport_express
      - device_tracker.philips_hue
      # - device_tracker.pioneer_vsx_924
      - device_tracker.playstation_4
      - device_tracker.qnap_nas
      - device_tracker.roku_stick
      - device_tracker.sofa_airport_express
      - device_tracker.sony_bravia
      - device_tracker.superhub_lan
      - device_tracker.superhub_wan
      - device_tracker.tim_houghton_s_dig_l21hn
      # - device_tracker.tim_s_ipad_4
      # - device_tracker.tim_s_ipad_7
      # - device_tracker.timh_apple_watch
      # - device_tracker.timh_applewatch
      # - device_tracker.timh_imac_retina
      # - device_tracker.timh_iphonex
      # - device_tracker.timh_iphonex_2
      # - device_tracker.timhiphonex
      # - device_tracker.tims_ipad_4
      - device_tracker.tp_link_deco_mesh_living_room
      - device_tracker.tp_link_deco_mesh_office
      - device_tracker.tp_link_wifi_router
      - device_tracker.xbox_360
      - device_tracker.xbox_systemos
      - device_tracker.xiaomi_gateway
      - device_tracker.youview_box
# mac sensors
      # - sensor.mac_cpu_idle_percent
      # - sensor.mac_cpu_idle_percent_output
      # - sensor.mac_memory_free_output
      # - sensor.mac_memory_private
      # - sensor.mac_memory_resident
      # - sensor.mac_memory_shared
      # - sensor.mac_memory_usage_output
      # - sensor.mac_network_downloaded
      # - sensor.mac_network_uploaded
      # - sensor.mac_uptime_days
      # - sensor.mac_uptime_hours
      # - sensor.mac_uptime_in_hours
      # - sensor.mac_uptime_minutes
      # - sensor.speedtest_download
      # - sensor.speedtest_download_data
      # - sensor.speedtest_ping
      # - sensor.speedtest_ping_data
      # - sensor.speedtest_upload
      # - sensor.speedtest_upload_data
      - sensor.itunes_shuffle_status
      - sensor.itunes_shuffle_status_raw
      - sensor.itunes_repeat_status
      - sensor.itunes_repeat_status_raw
# iOS device sensors
      - sensor.sim_1
      - sensor.sim_1_2
      - sensor.ssid
      - sensor.ssid_2
      - sensor.ssid_3
      - sensor.ssid_4
      - sensor.bssid
      - sensor.bssid_2
      - sensor.bssid_3
      - sensor.bssid_4
      - sensor.steps
      - sensor.steps_2
      - sensor.average_active_pace
      - sensor.average_active_pace_2
      - sensor.battery_level
      - sensor.battery_level_2
      - sensor.battery_level_3
      - sensor.battery_level_4
      - sensor.battery_state
      - sensor.battery_state_2
      - sensor.battery_state_3
      - sensor.battery_state_4
      - sensor.connection_type
      - sensor.connection_type_2
      - sensor.connection_type_3
      - sensor.connection_type_4
      - sensor.distance
      - sensor.distance_2
      - sensor.floors_ascended
      - sensor.floors_ascended_2
      - sensor.floors_descended
      - sensor.floors_descended_2
      - sensor.geocoded_location
      - sensor.geocoded_location_2
      - sensor.geocoded_location_3
      - sensor.geocoded_location_4

