

###############################################################
#   Warnings at certain times
###############################################################

# Lawn mower stuck Daylight Savings Time
# sensor.is_dst is a template integration
- alias: Check lawnmower is stuck DST
  trigger:
    - platform: time
      at:
        - "09:07"      
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.tuya_smart_plug_13_power
        below: 25
      - condition: state
        entity_id: sensor.is_dst
        state: '0'
      # only in Nov, Dec, Jan, Feb
      - condition: template
        # value_template: '{{ now().month in [1,2,11,12] }}'
        value_template: '{{ now().month > 2 and now().month < 11 }}'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.dining_room_speaker
        volume_level: 0.4
    - delay: 00:00:01
    - service: script.house_announce_downstairs
      data_template:
        notification_feed_name: LawnmowerCharging
        tts_msg: "The lawnmower should be charging now, but I do not detect any power draw in the shed."
    - service: notify.telegram_timhiphonex
      data:
        title: 'Alert! - Lawnmower'
        message: "The lawnmower is not charging"
# Lawn mower stuck not Daylight Savings Time
- alias: Check lawnmower is stuck not DST
  trigger:
    - platform: time
      at:
        - "10:07"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.tuya_smart_plug_13_power
        below: 25
      - condition: state
        entity_id: sensor.is_dst
        state: '1'
      # only in Nov, Dec, Jan, Feb
      - condition: template
        # value_template: '{{ now().month in [1,2,11,12] }}'
        value_template: '{{ now().month >= 11 or now().month <= 2 }}'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.dining_room_speaker
        volume_level: 0.4
    - delay: 00:00:01
    - service: script.house_announce_downstairs
      data_template:
        notification_feed_name: LawnmowerCharging
        tts_msg: "The lawnmower should be charging now, but I do not detect any power draw in the shed."
    - service: notify.telegram_timhiphonex
      data:
        title: 'Alert! - Lawnmower'
        message: "The lawnmower is not charging"


# Plant moisture check
- alias: Plants moisture check
  trigger:
    - platform: time_pattern
      hours: '13'
      minutes: '/28'
  condition:
    condition: template
    value_template: >-
      {%- set moisture_alert_threshold = 10|int -%}
      {{ states.plant | selectattr('attributes.moisture', 'defined') | selectattr('attributes.moisture','<', moisture_alert_threshold ) | list | count >= 1 }}
  action:
    - service: notify.telegram_timhiphonex
      data_template:
        title: "Plants low moisture warning"
        message: >-
          {%- set moisture_alert_threshold = 10|int -%}
          {%- set low_moisture = states.plant | selectattr('attributes.moisture', 'defined') | selectattr('attributes.moisture','<', moisture_alert_threshold ) | map(attribute='name') | list | join(', ') -%}
          Low moisture for the following plants: {{ low_moisture }}

# - alias: Check plant 1 moisture levels
#   trigger:
#     - platform: time_pattern
#       hours: '13'
#       minutes: '/16'
#   condition:
#     condition: numeric_state
#     entity_id: sensor.hasubsystem_ble_moisture_80eaca890d06
#     below: 10
#   action:
#     - service: notify.pushover_timhiphonex
#       data_template:
#         message: "Plant 1 moisture levels are low. Current moisture is at {{ states.sensor.hasubsystem_ble_moisture_80eaca890d06.state }} percent"
# - alias: Check plant 2 moisture levels
#   trigger:
#     - platform: time_pattern
#       hours: '13'
#       minutes: '/16'
#   condition:
#     condition: numeric_state
#     entity_id: sensor.hasubsystem_ble_moisture_c47c8d6c6289
#     below: 10
#   action:
#     - service: notify.pushover_timhiphonex
#       data_template:
#         message: "Plant 2 moisture levels are low. Current moisture is at {{ states.sensor.hasubsystem_ble_moisture_c47c8d6c6289.state }} percent"
# - alias: Check plant 3 moisture levels
#   trigger:
#     - platform: time_pattern
#       hours: '13'
#       minutes: '/16'
#   condition:
#     condition: numeric_state
#     entity_id: sensor.hasubsystem_ble_moisture_c47c8d6c697e
#     below: 10
#   action:
#     - service: notify.pushover_timhiphonex
#       data_template:
#         message: "Plant 3 moisture levels are low. Current moisture is at {{ states.sensor.hasubsystem_ble_moisture_c47c8d6c697e.state }} percent"
# - alias: Check plant 4 moisture levels
#   trigger:
#     - platform: time_pattern
#       hours: '13'
#       minutes: '/16'
#   condition:
#     condition: numeric_state
#     entity_id: sensor.hasubsystem_ble_moisture_c47c8d6c68dc
#     below: 10
#   action:
#     - service: notify.pushover_timhiphonex
#       data_template:
#         message: "Plant 4 moisture levels are low. Current moisture is at {{ states.sensor.hasubsystem_ble_moisture_c47c8d6c68dc.state }} percent"
# - alias: Check plant 5 moisture levels
#   trigger:
#     - platform: time_pattern
#       hours: '13'
#       minutes: '/16'
#   condition:
#     condition: numeric_state
#     entity_id: sensor.hasubsystem_ble_moisture_c47c8d6c5d99
#     below: 10
#   action:
#     - service: notify.pushover_timhiphonex
#       data_template:
#         message: "Plant 5 moisture levels are low. Current moisture is at {{ states.sensor.hasubsystem_ble_moisture_c47c8d6c5d99.state }} percent"
# - alias: Check plant 6 moisture levels
#   trigger:
#     - platform: time_pattern
#       hours: '13'
#       minutes: '/16'
#   condition:
#     condition: numeric_state
#     entity_id: sensor.hasubsystem_ble_moisture_c47c8d6c695d
#     below: 10
#   action:
#     - service: notify.pushover_timhiphonex
#       data_template:
#         message: "Plant 6 moisture levels are low. Current moisture is at {{ states.sensor.hasubsystem_ble_moisture_c47c8d6c695d.state }} percent"


###############################################################
#   Update current time and date every 10 minutes (approx, for Apple Watch UI)
###############################################################
# - alias: 'Update current time and date sensor every 10 minutes'
#   trigger:
#     - platform: time_pattern
#       minutes: '/10'
#   action:
#     - service: homeassistant.update_entity
#       entity_id: sensor.current_time_date

###############################################################
#   Keep Google Minis awake to stop 'bong' noise when it wakes up
###############################################################
- alias: Keep downstairs Google Mini awake
  trigger:
    platform: time_pattern
    minutes: "/2"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.dining_room_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.dining_room_speaker
        state: 'idle'
  action:
    - service: media_player.play_media
      data_template:                 
        entity_id: media_player.dining_room_speaker            
        media_content_id: http://192.168.0.8:8888/mp3/silence-1sec.mp3
        media_content_type: 'audio/mp3'
- alias: Keep upstairs Google Mini awake
  trigger:
    platform: time_pattern
    minutes: "/2"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.landing_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.landing_speaker
        state: 'idle'
  action:
    - service: media_player.play_media
      data_template:                 
        entity_id: media_player.landing_speaker            
        media_content_id: http://192.168.0.8:8888/mp3/silence-1sec.mp3
        media_content_type: 'audio/mp3'
###############################################################
#   My bedside light flash lights when snoozing alarm, triggered by iOS shortcut automation
###############################################################
# - alias: "Bedside light snooze timer flashing"
#   trigger: 
#     platform: state
#     entity_id: input_boolean.flashing_bedside_lamp
#     to: "on"
#   action:
#     - service: script.turn_on
#       data:
#         entity_id: script.bedside_light_snooze_timer_flashing
#     - service: switch.turn_off
#       entity_id: switch.tuya_smart_plug_02
###############################################################
#   Turn off bedroom fan
###############################################################
#- alias: 'Turn off bedroom fan'
#  trigger:
#    platform: time
#    at: "08:00:00"
#  action:
#    service: switch.turn_off
#    entity_id: switch.tuya_smart_plug_02
#- alias: 'Turn off bedroom fan backup'
#  trigger:
#    platform: time
#    at: "08:30:00"
#  action:
#    service: switch.turn_off
#    entity_id: switch.tuya_smart_plug_02
###############################################################
####   Record last_updated time for Xiaomi motion sensors   ### 
###############################################################
- alias: "Downstairs loo motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d0002247bba
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.downstairs_loo_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
- alias: "Porch motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d0003f131cf
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.porch_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
- alias: "Kitchen motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d0004239af0
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.kitchen_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
- alias: "Tim motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d000484379e
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.tim_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
- alias: "Fin motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d00047b92a8
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.fin_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
- alias: "Jed motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d00047b936c
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.jed_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"