###############################################################
####    Timer for Grow light & fan (grow mode)              ### 
###############################################################

##
## Check Meross power strip for availability
##
- alias: 'Meross power strip unavailable'
  trigger:
    - platform: state
      entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
      to: 'unavailable'
      for:
        minutes: 15
  action:
    repeat:
      sequence:
        # - service: notify.pushover_timhiphonex
        #   data_template:
        #     message: "The Meross power strip has been unavailable for 2 hours!"
        - service: notify.mobile_app_timh_iphonex256
          data:
            message: "The Meross power strip has been unavailable for 15 minutes, attempting to reload."
        - service: homeassistant.turn_on
          entity_id: script.reload_integration_meross
        - delay:
            minutes: 10
      until:
        condition: or
        conditions:
          - condition: state
            entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
            state: 'off'
          - condition: state
            entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
            state: 'on'
##
## Turn light on at 7pm
##
- alias: 'Grow light on'
  trigger:
    - platform: time_pattern
      hours: '19'
      minutes: '/5'
      seconds: '00'
    - platform: state
      entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
      from: 'unavailable'
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'on'
      - condition: time
        after: '19:00:00'
        before: '07:00:00'
      - condition: template
        value_template: >
          {{ is_state('switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2', 'off') }}
  action:
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
    
##
## Turn light off at 7am
##
- alias: 'Grow light off'
  trigger:
    - platform: time_pattern
      hours: '07'
      minutes: '/5'
      seconds: '00'
    - platform: state
      entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
      from: 'unavailable'
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'on'
      - condition: time
        after: '07:00:00'
        before: '19:00:00'
      - condition: template
        value_template: >
          {{ is_state('switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2', 'on') }}
  action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
###############################################################
####    Timer for Grow light & fan (grow mode)              ### 
###############################################################
#- alias: 'Grow light on backup'
#  trigger:
#    platform: time_pattern
#    hours: '15'
#    minutes: '/5'
#    seconds: '00'
#  condition:
#    condition: and
#    conditions: 
#      - condition: state
#        entity_id: input_boolean.plants_grow_mode
#        state: 'on'
#      - condition: template
#        value_template: >
#          {{ is_state('switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2', 'off') }}
#  action:
#  - service: switch.turn_on
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#  - service: switch.turn_on
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
#    
#- alias: 'Grow light off backup'
#  trigger:
#    platform: time_pattern
#    hours: '11'
#    minutes: '/5'
#    seconds: '00'
#  condition:
#    condition: and
#    conditions: 
#      - condition: state
#        entity_id: input_boolean.plants_grow_mode
#        state: 'on'
#      - condition: template
#        value_template: >
#          {{ is_state('switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2', 'on') }}
#  action:
#  - service: switch.turn_off
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#  - service: switch.turn_off
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
      
#- alias: 'Grow light on backup 2'
#  trigger:
#    platform: time
#    at: '15:10:00'
#  condition:
#    condition: state
#    entity_id: input_boolean.plants_grow_mode
#    state: 'on'
#  action:
#  - service: switch.turn_on
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#  - service: switch.turn_on
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
#    
#- alias: 'Grow light off backup'
#  trigger:
#    platform: time
#    at: '11:10:00'
#  condition:
#    condition: state
#    entity_id: input_boolean.plants_grow_mode
#    state: 'on'
#  action:
#  - service: switch.turn_off
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#  - service: switch.turn_off
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
###############################################################
####             Timer for fan (drying mode)           ### 
###############################################################
#- alias: 'Fan on drying mode'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.aqara_loft_temperature
#    # Optional
#    # value_template: "{{ state.attributes.battery }}"
#    # At least one of the following required
#    above: 22
#    below: 99
#  condition:
#    condition: state
#    entity_id: input_boolean.plants_grow_mode
#    state: 'off'
#  action:
#  - service: switch.turn_on
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
#- alias: 'Fan off drying mode'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.aqara_loft_temperature
#    # Optional
#    # value_template: "{{ state.attributes.battery }}"
#    # At least one of the following required
#    below: 18
#    above: 0
#  condition:
#    condition: state
#    entity_id: input_boolean.plants_grow_mode
#    state: 'off'
#  action:
#  - service: switch.turn_off
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
###############################################################
####      Backup timer for Grow light if Unavailable        ### 
###############################################################
#- alias: 'Grow light timer off backup'
#  trigger:
#  - platform: state
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#    from: 'unavailable'
#  condition:
#    condition: and
#    conditions: 
#      - condition: time
#        after: '11:00:00'
#        before: '15:00:00'
#      - condition: state
#        entity_id: input_boolean.plants_grow_mode
#        state: 'on'
#  action:
#  - service: switch.turn_off
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#  - service: switch.turn_off
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
#- alias: 'Grow light timer on backup'
#  trigger:
#  - platform: state
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#    from: 'unavailable'
#  condition:
#    condition: and
#    conditions: 
#      - condition: time
#        after: '15:00:00'
#        before: '11:00:00'
#      - condition: state
#        entity_id: input_boolean.plants_grow_mode
#        state: 'on'
#  action:
#  - service: switch.turn_on
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_2
#  - service: switch.turn_on
#    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_4
###############################################################
#   Humidity pump (grow mode)
###############################################################
- alias: "Pump on when humidity too high"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_humidity_a4c138174b0b
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    above: 55
    below: 99
  condition:
    condition: state
    entity_id: input_boolean.plants_grow_mode
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
- alias: "Pump off when humidity too low"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_humidity_a4c138174b0b
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    below: 40
    above: 10
  condition:
    condition: state
    entity_id: input_boolean.plants_grow_mode
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
###############################################################
#   Humidity pump (drying mode)
###############################################################
- alias: "Pump on when humidity too high drying mode"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_humidity_a4c138174b0b
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    above: 55
    below: 99
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
- alias: "Pump off when humidity too low drying mode"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_humidity_a4c138174b0b
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    below: 45
    above: 10
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
###############################################################
#   Humidity pump (drying mode final stage)
###############################################################
- alias: "Pump on when humidity too high drying mode final"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_humidity_a4c138174b0b
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    above: 63
    below: 99
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
- alias: "Pump off when humidity too low drying mode final"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_humidity_a4c138174b0b
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    below: 55
    above: 10
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
###############################################################
#   Heater control (grow mode) + add extractor for Summer
###############################################################
- alias: "Heater off when temp too high"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_temperature_a4c13815523d
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    above: 24
    below: 99
  condition:
    condition: state
    entity_id: input_boolean.plants_grow_mode
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_3
  # testing extractor, will conflict with humidity detection
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_5
- alias: "Heater on when temp too low"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_temperature_a4c13815523d
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    below: 20
    above: 0
  condition:
    condition: state
    entity_id: input_boolean.plants_grow_mode
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_3
###############################################################
#   Heater control (drying mode)
###############################################################
- alias: "Heater off when temp too high drying mode"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_temperature_a4c13815523d
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    above: 23
    below: 99
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_3
- alias: "Heater on when temp too low drying mode"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_temperature_a4c13815523d
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    below: 20
    above: 0
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_3
###############################################################
#   Heater control (drying mode final stage)
###############################################################
- alias: "Heater off when temp too high drying mode final"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_temperature_a4c13815523d
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    above: 18
    below: 99
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_3
- alias: "Heater on when temp too low drying mode final"
  trigger:
    platform: numeric_state
    entity_id: sensor.hasubsystem_ble_temperature_a4c13815523d
    # Optional
    # value_template: "{{ state.attributes.battery }}"
    # At least one of the following required
    below: 17
    above: 0
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.plants_grow_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.plants_drying_mode
        state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.smart_switch_1911296783282590805448e1e9121f70_outlet_3
###############################################################
####             Timer for Dragon plant light               ### 
###############################################################
- alias: 'Dragon plant light on'
  trigger:
    platform: time
    at:
      - "08:45"
      - "08:50"
      - "08:55"
      - "09:00"
      - "10:00"
      - "11:00"
      - "12:00"
      - "13:00"
      - "14:00"
      - "15:00"
      - "16:00"
      - "17:00"
  action:
    service: switch.turn_on
    entity_id: switch.tuya_smart_plug_14
- alias: 'Dragon plant light off'
  trigger:
    platform: time
    at:
      - "18:15"
      - "18:20"
      - "18:25"
      - "18:30"
      - "19:30"
      - "20:30"
      - "21:30"
      - "22:30"
      - "23:30"
      - "00:30"
      - "01:30"
      - "02:30"
      - "03:30"
      - "04:30"
      - "05:30"
      - "06:30"
      - "07:30"
  action:
    service: switch.turn_off
    entity_id: switch.tuya_smart_plug_14