###############################################################
####             Overnight routine                          ### 
###############################################################
- alias: 'Shield Pro overnight restart'
  trigger:
    - platform: time
      at:
        - "04:45"
        - "04:50"
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: media_player.shield
        state: 'off'
      - condition: state
        entity_id: media_player.sony_bravia_tv
        state: 'off'
  action:
    # - service: homeassistant.turn_on
    #   data:
    #     entity_id: media_player.shield
    # - delay:
    #     seconds: 10
    - service: homeassistant.turn_on
      data:
        entity_id: script.shield_pro_restart
    - service: persistent_notification.create
      data:
        message: "Shield Pro restarted at {{ trigger.to_state.state }}"
        title: "Shield restart"

###############################################################
####             Wall mount battery warning                 ### 
###############################################################
- alias: 'Wall mount battery warning'
  trigger:
    platform: numeric_state
    entity_id: sensor.wallmount_battery_level
    below: 30
  condition:
    condition: state
    entity_id: sensor.wallmount_battery_state
    state: 'discharging'
  action:
  - service: persistent_notification.create
    data:
      message: "Wall mount battery level is {{ trigger.to_state.state }}%"
      title: "Battery warning"
  - service: notify.mobile_app_timh_iphonex256
    data:
      message: "Wall mount battery level is {{ trigger.to_state.state }}%"
- alias: 'Jed Android battery warning'
  trigger:
    platform: numeric_state
    entity_id: sensor.dig_l21hn_battery_level
    below: 30
  condition:
    condition: state
    entity_id: sensor.dig_l21hn_battery_state
    state: 'discharging'
  action:
  - service: persistent_notification.create
    data:
      message: "Jed Android battery level is {{ trigger.to_state.state }}%"
      title: "Battery warning"
  - service: notify.mobile_app_timh_iphonex256
    data:
      message: "Jed Android battery level is {{ trigger.to_state.state }}%"
###############################################################
####             Morning routine                            ### 
###############################################################

- alias: 'Morning routine'
  trigger:
    - platform: time
      at:
        - "06:00"
  # condition:
  #   condition: and
  #   conditions: 
  #     - condition: time
  #       weekday:
  #         - mon
  #         - tue
  #         - wed
  #         - thu
  #         - fri
  #         - sat
  #         - sun
  #     - condition: state
  #       entity_id: media_player.kitchen_roku
  #       state: 'idle'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: script.lighting_scene_morning_initialisation

- alias: 'Morning BBC News in the kitchen'
  trigger:
    - platform: time
      at:
        - "09:15"
  condition:
    condition: and
    conditions: 
      - condition: time
        weekday:
          - mon
          - tue
          - thu
      - condition: state
        entity_id: media_player.kitchen_roku
        state: 'idle'
  action:
    # news on kitchen tv
    - service: homeassistant.turn_on
      data:
        entity_id: switch.tuya_smart_plug_11
    - delay:
        seconds: 5
    - service: homeassistant.turn_on
      data:
        entity_id: script.roku_bbc_news

- alias: 'Morning News Briefing in my bedroom'
  trigger:
    - platform: time
      at:
        - "09:10"
  condition:
    condition: and
    conditions: 
      - condition: time
        weekday:
          - mon
          - tue
          - thu
      - condition: state
        entity_id: media_player.tim_echo_dot
        state: 'standby'
  action:
    # news on tim bedroom echo
    - service: media_player.play_media
      data:
        entity_id: media_player.tim_echo_dot
        media_content_type: sequence
        media_content_id: Alexa.FlashBriefing.Play

- alias: 'Morning News Briefing in the office'
  trigger:
    - platform: time
      at:
        - "09:20"
  condition:
    condition: and
    conditions: 
      - condition: time
        weekday:
          - mon
          - tue
          - thu
      - condition: state
        entity_id: media_player.office_echo_show
        state: 'standby'
  action:
    # news on office echo show
    - service: media_player.play_media
      data:
        entity_id: media_player.office_echo_show
        media_content_type: sequence
        media_content_id: Alexa.FlashBriefing.Play

###############################################################
####             Evening routine                            ### 
###############################################################
- alias: 'Lights in the evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:00:00'
  condition:
    condition: and
    conditions: 
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
      - condition: state
        entity_id: person.tim
        state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hue_color_candle_1
        brightness: 173
        transition: 3
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.random_light_dining_room_wall_wash
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.random_light_reading_light
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.random_light_living_room_sofa
    # Christmas lights
    # - service: homeassistant.turn_on
    #   data:
    #     entity_id: switch.tuya_smart_plug_15

# Roku channels
# <app id="11703" type="appl" version="3.4.91000074">BBC iPlayer</app>
# <app id="13" type="appl" version="11.4.2020090921">Prime Video</app>
# <app id="42329" type="appl" version="2.4.1">ITV Hub</app>
# <app id="34785" type="appl" version="4.1.21">All 4</app>
# <app id="27424" type="appl" version="2.7.174">My5</app>
# <app id="151908" type="appl" version="2.9.42">The Roku Channel</app>
# <app id="27711" type="appl" version="3.4.91000050">BBC News</app>
# <app id="27181" type="appl" version="4.51.216">Sky News</app>
# <app id="50539" type="appl" version="1.0.16">Twitch</app>
# <app id="837" type="appl" version="1.0.93000097">YouTube</app>
# <app id="13535" type="appl" version="6.6.12">Plex - Stream for Free</app>
# <app id="40141" type="appl" version="3.4.91000054">BBC Sports</app>
# <app id="93580" type="appl" version="1.8.2">iWebTV Player</app>
# <app id="551012" type="appl" version="5.0.81">Apple TV</app>
# <app id="184661" type="appl" version="1.0.54">Roku Streaming Player Intro</app>
# <app id="296781" type="appl" version="1.0.1">Beauty wild nature</app>
# <app id="123095" type="appl" version="3.0.90000005">Aquatic Life</app>
# <app id="559429" type="appl" version="1.0.0">Adorable Baby Cats</app>