###############################################################
####              Fridge door warning                       ### 
###############################################################
- alias: Fridge door timer start
  trigger:
    platform: state
    entity_id: sensor.window_fridge
    to: 'Open'
  action:
  - service: timer.start
    data:
      entity_id: timer.fridge_door
- alias: Fridge door warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.fridge_door
  condition:
    condition: state
    entity_id: sensor.window_fridge
    state: 'Open'
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "The fridge <emphasis level='strong'>door</emphasis> is open."
    - service: timer.start
      data:
        entity_id: timer.fridge_door
###############################################################
####              Freezer door warning                       ### 
###############################################################
- alias: Freezer door timer start
  trigger:
    platform: state
    entity_id: sensor.window_freezer
    to: 'Open'
  action:
  - service: timer.start
    data:
      entity_id: timer.freezer_door
- alias: Freezer door warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.freezer_door
  condition:
    condition: state
    entity_id: sensor.window_freezer
    state: 'Open'
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "The freezer door is open."
        mplayer: "kitchen_echo_show"
    - service: timer.start
      data:
        entity_id: timer.freezer_door
###############################################################
####             Side alley gate warning                    ### 
###############################################################
- alias: Freezer door timer start
  trigger:
    platform: state
    entity_id: sensor.window_side_alley_gate
    to: 'Open'
  action:
  - service: timer.start
    data:
      entity_id: timer.side_alley_gate
- alias: Freezer door warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.side_alley_gate
  condition:
    condition: state
    entity_id: sensor.window_side_alley_gate
    state: 'Open'
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "The side alley gate is open."
    - service: timer.start
      data:
        entity_id: timer.side_alley_gate
###############################################################
####              Left shed door warning                    ### 
###############################################################
- alias: Left shed door timer start
  trigger:
    platform: state
    entity_id: sensor.window_left_shed_door
    to: 'Open'
  action:
  - service: timer.start
    data:
      entity_id: timer.left_shed_door
- alias: Freezer door warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.left_shed_door
  condition:
    condition: state
    entity_id: sensor.window_left_shed_door
    state: 'Open'
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "The left shed door is open."
    - service: timer.start
      data:
        entity_id: timer.left_shed_door
###############################################################
####              Right shed door warning                    ### 
###############################################################
- alias: Right shed door timer start
  trigger:
    platform: state
    entity_id: sensor.window_right_shed_door
    to: 'Open'
  action:
  - service: timer.start
    data:
      entity_id: timer.right_shed_door
- alias: Freezer door warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.right_shed_door
  condition:
    condition: state
    entity_id: sensor.window_right_shed_door
    state: 'Open'
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "The right shed door is open."
    - service: timer.start
      data:
        entity_id: timer.right_shed_door
###############################################################
####              Front door warning                    ### 
###############################################################
- alias: Front door timer start
  trigger:
    platform: state
    entity_id: sensor.window_front_door
    to: 'Open'
  action:
  - service: timer.start
    data:
      entity_id: timer.front_door
- alias: Front door warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.front_door
  condition:
    condition: state
    entity_id: sensor.window_front_door
    state: 'Open'
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "The front door is open."
    - service: timer.start
      data:
        entity_id: timer.front_door