###############################################################
####             Plex play notifications on iOS app         ### 
###############################################################
- alias: "Plex play notification"
  trigger:
    platform: state
    entity_id: sensor.plex_tim_s_imac
  action:
#    service: notify.ios_timiphonex
#    service: notify.pushover_timhiphonex
    service: notify.mobile_app_timh_iphonex
    data_template:
      message: >
        {% for attr in states.sensor.plex_tim_s_imac.attributes %}
        {%- if not attr=="friendly_name" and not attr=="unit_of_measurement" and not attr=="icon" -%}
         {{attr}} is watching {{states.sensor.plex_tim_s_imac.attributes[attr]}}. 
         
         {{- '\n' -}}
        {%- endif %}
        {%- endfor -%}
###############################################################
####         iPhone notification with response              ###
###############################################################
- alias: When Fin gets home, inform Tim Phone
  initial_state: True
  trigger:
    platform: state
    entity_id: device_tracker.iphonedetect_fin_iphone6
    from: 'not_home'
    to: 'home'
  action:
    service: notify.mobile_app_timh_iphonex
    data:
      message: "Fin has arrived home."
      data:
        push:
          badge: 1
          # sound: <SOUND FILE HERE>
          category: "finarriveshome" # Needs to match the top level identifier you used in the ios configuration  - Don't forget to 'Update push settings' on the iOS app!
        action_data: # Anything passed in action_data will get echoed back to Home Assistant.
          entity_id: light.test
          my_custom_data: foo_bar
# Tell Kitchen Echo to say Welcome Home
- alias: Welcome home
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: WELCOME_HOME
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "Welcome home Fin!"
# Type a response on phone for Kitchen Echo to read out
- alias: Welcome message
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: WELCOME_MESSAGE
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "{{ trigger.event.data['textInput'] }}"
###############################################################
####         iPhone notification test              ###
###############################################################
- alias: Notifications test
  initial_state: True
  trigger:
    platform: state
    entity_id:  light.bedside_lamp
    from: 'off'
    to: 'on'
  action:
    service: notify.mobile_app_timh_iphonex
    data:
      message: "Notifications test triggered."
      data:
        push:
          badge: 1
          # sound: <SOUND FILE HERE>
          category: "notificationtest" # Needs to match the top level identifier you used in the ios configuration  - Don't forget to 'Update push settings' on the iOS app!
        action_data: # Anything passed in action_data will get echoed back to Home Assistant.
          entity_id: light.test
          my_custom_data: foo_bar
# Tell Kitchen Echo to say Notification test
- alias: Notification test
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: NOTIFICATION_TEST
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "Notification test"
# Type a response on phone for Kitchen Echo to read out
- alias: Notification alternative
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: NOTIFICATION_ALTERNATIVE
  action:
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "{{ trigger.event.data['textInput'] }}"
