###############################################################
####             Timer for Grow light                ### 
###############################################################
- alias: 'Grow light on'
  trigger:
    platform: time
    at: '15:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.plants_power_strip_switch_1
  - service: switch.turn_on
    entity_id: switch.plants_power_strip_switch_3
- alias: 'Grow light off'
  trigger:
    platform: time
    at: '11:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.plants_power_strip_switch_1
  - service: switch.turn_off
    entity_id: switch.plants_power_strip_switch_3
###############################################################
####      Backup timer for Grow light if Unavailable        ### 
###############################################################
- alias: 'Grow light timer off backup'
  trigger:
  - platform: state
    entity_id: switch.plants_power_strip_switch_1
    from: 'unavailable'
  condition:
    condition: time
    after: '11:00:00'
    before: '15:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.plants_power_strip_switch_1
  - service: switch.turn_off
    entity_id: switch.plants_power_strip_switch_3
- alias: 'Grow light timer on backup'
  trigger:
  - platform: state
    entity_id: switch.plants_power_strip_switch_1
    from: 'unavailable'
  condition:
    condition: time
    after: '15:00:00'
    before: '11:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.plants_power_strip_switch_1
  - service: switch.turn_on
    entity_id: switch.plants_power_strip_switch_3
###############################################################
####             Timer for Dragon plant light               ### 
###############################################################
- alias: 'Dragon plant light on'
  trigger:
    platform: time
    at: '08:45:00'
  action:
    service: switch.turn_on
    entity_id: switch.58850130a4cf12a6aeb2
- alias: 'Dragon plant light off'
  trigger:
    platform: time
    at: '18:15:00'
  action:
    service: switch.turn_off
    entity_id: switch.58850130a4cf12a6aeb2