###############################################################
#   Alexa timers
###############################################################
- alias: "Kitchen timer announcement"
  trigger: 
    platform: state
    entity_id: sensor.kitchen_echo_show_next_timer
  condition: 
    condition: template
    value_template: "{{ trigger.to_state.state != 'unavailable' and trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: script.turn_off
      data:
        entity_id: script.alexa_timer_check
    - service: script.alexa_timer_check
      data_template:
        duration: "{{ (as_timestamp(trigger.to_state.state) - now().timestamp() + 5) | timestamp_custom('%H:%M:%S', false) }}"

###############################################################
#   Turn off bedroom fan
###############################################################
- alias: 'Turn off bedroom fan'
  trigger:
    platform: time
    at: "08:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.17336502840d8ebe7482
- alias: 'Turn off bedroom fan backup'
  trigger:
    platform: time
    at: "08:30:00"
  action:
    service: switch.turn_off
    entity_id: switch.17336502840d8ebe7482
###############################################################
####   Record last_updated time for Xiaomi motion sensors   ### 
###############################################################
- alias: "Downstairs loo motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d0002247bba
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.downstairs_loo_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
- alias: "Porch motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d0003f131cf
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.porch_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
- alias: "Kitchen motion sensor record time triggered"
  initial_state: true
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d0004239af0
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.kitchen_motion_sensor_last_updated
    data_template:
      time: "{{ (now().timestamp()+(60*60))|timestamp_custom('%H:%M:%S') }}"
      date: "{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d') }}"
###############################################################
####               Kitchen flood warning                    ### 
###############################################################
- alias: Kitchen flood sensor timer start
  trigger:
    platform: state
    entity_id: sensor.flood_sensor_kitchen
    to: 'on'
  action:
  - service: timer.start
    data:
      entity_id: timer.flood_sensor_kitchen
- alias: Kitchen flood warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.flood_sensor_kitchen
  condition:
    condition: state
    entity_id: sensor.flood_sensor_kitchen
    state: 'on'
  action:
    - service: script.house_announce_echos
      data_template:
        tts_msg: "I am detecting a water leak under the dishwasher."
    - service: notify.pushover_timhiphonex
      data_template:
        message: "I am detecting a water leak under the dishwasher."
    - service: timer.start
      data:
        entity_id: timer.flood_sensor_kitchen
###############################################################
####               Bath flood warning                    ### 
###############################################################
- alias: Bath flood sensor timer start
  trigger:
    platform: state
    entity_id: sensor.flood_sensor_bath
    to: 'on'
  action:
  - service: timer.start
    data:
      entity_id: timer.flood_sensor_bath
- alias: Bath flood warning
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.flood_sensor_bath
  condition:
    condition: state
    entity_id: sensor.flood_sensor_bath
    state: 'on'
  action:
    - service: script.house_announce_echos
      data_template:
        tts_msg: "I am detecting a water leak under the bath."
    - service: notify.pushover_timhiphonex
      data_template:
        message: "I am detecting a water leak under the bath."
    - service: timer.start
      data:
        entity_id: timer.flood_sensor_bath
################################################################
#### Turn on Kitchen light when motion detected ### 
################################################################
- alias: Turn on Kitchen light when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0004239af0
    to: 'on'
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: switch.wall_switch_left_158d00030a7792
        state: 'off'
      - condition: state
        entity_id: switch.wall_switch_right_158d00030a7792
        state: 'off'
      - condition: state
        entity_id: switch.wall_switch_left_158d0003669ca2
        state: 'off'
      - condition: state
        entity_id: switch.wall_switch_right_158d0003669ca2
        state: 'off'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: 
      - switch.wall_switch_left_158d00030a7792
      - switch.wall_switch_right_158d0003669ca2


################################################################
#### Turn off Kitchen light after 3 mins if no motion ### 
################################################################
- alias: Start kitchen timer
  trigger:
    - platform: state
      entity_id: switch.wall_switch_left_158d00030a7792
      to: 'on'
    - platform: state
      entity_id: switch.wall_switch_right_158d00030a7792
      to: 'on'
    - platform: state
      entity_id: switch.wall_switch_left_158d0003669ca2
      to: 'on'
    - platform: state
      entity_id: switch.wall_switch_right_158d0003669ca2
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.kitchen_timer_disable
    state: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.kitchen
- alias: Reset kitchen timer on movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0004239af0
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.kitchen_timer_disable
    state: 'off'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.kitchen
    - service: timer.start
      data:
        duration: 00:10:00
        entity_id: timer.kitchen
- alias: Turn off kitchen light after timer
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen
  condition:
    condition: state
    entity_id: binary_sensor.motion_sensor_158d0004239af0
    state: 'off'
  action:
    service: homeassistant.turn_off
    data:
      entity_id: 
      - switch.wall_switch_left_158d00030a7792
      - switch.wall_switch_right_158d00030a7792
      - switch.wall_switch_left_158d0003669ca2
      - switch.wall_switch_right_158d0003669ca2
################################################################
#### Turn on Downstairs loo light when motion detected ### 
################################################################
- alias: Turn on Downstairs loo light when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002247bba
    to: 'on'
  condition:
    condition: state
    entity_id: switch.wall_switch_158d000309dd3f
    state: 'off'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: switch.wall_switch_158d000309dd3f
################################################################
#### Turn off Downstairs loo light after 3 mins if no motion ### 
################################################################
- alias: Start downstairs loo timer
  trigger:
    platform: state
    entity_id: switch.wall_switch_158d000309dd3f
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.downstairs_loo_timer_disable
    state: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.downstairsloo
- alias: Reset downstairs loo timer on movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002247bba
    to: 'on'
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.downstairs_loo_timer_disable
        state: 'off'
      - condition: state
        entity_id: timer.downstairsloo
        state: 'active'
  action:
  - service: timer.start
    data:
      entity_id: timer.downstairsloo
- alias: Turn off loo after timer
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.downstairsloo
  condition:
    condition: state
    entity_id: binary_sensor.motion_sensor_158d0002247bba
    state: 'off'
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.wall_switch_158d000309dd3f
################################################################
#### Turn on Porch light when motion detected ### 
################################################################
- alias: Turn on Porch light when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0003f131cf
    to: 'on'
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.doorbell_mode
  - service: timer.start
    data:
      entity_id: timer.porch
################################################################
#### Turn off Porch light after 1 minute ### 
################################################################
- alias: Turn off Porch light after timer
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.porch
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.porch_off
########################################################################
########     Turn off office lights 3 minutes after motion     #########
########################################################################
- alias: Turn on office light when movement detected
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion_sensor
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '17:30'
        before: '04:30'
      - condition: state
        entity_id: input_boolean.office_motion_sensor_toggle
        state: 'on'
  action:
    service: script.turn_on
    entity_id: script.work_mode_delayed_office

- alias: Turn off office light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion_sensor
    to: 'off'
    for:
      minutes: 3
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '17:30'
        before: '04:30'
      - condition: state
        entity_id: input_boolean.office_motion_sensor_toggle
        state: 'on'
  action:
    service: script.turn_on
    entity_id: script.game_mode_delayed_office