########################################################
## CONFIG
########################################################


########################################################
## SENSORS
########################################################
sensor:

########################################################
## SCRIPTS
########################################################
script:

  alexa_timer_announce:
    alias: "Kitchen Timer Announcement Loop"
    mode: restart
    sequence:    
      - delay: '{{ duration }}'
      - repeat:
          while:
            - condition: template
              value_template: '{{ states("sensor.kitchen_echo_show_next_timer") not in ["None",
                "unknown", "unavailable"] and as_timestamp(states("sensor.kitchen_echo_show_next_timer"))
                < as_timestamp(now()) }}'
          sequence:
            - service: script.house_announce_downstairs
              data_template:
                notification_feed_name: KitchenTimer
                tts_msg: "The kitchen timer is going off"
            - delay:
                seconds: 15


########################################################
## AUTOMATIONS
########################################################
automation:
- alias: Kitchen Timer Announcement
  mode: parallel
  trigger:
    platform: state
    entity_id: sensor.kitchen_echo_show_next_timer
  condition:
    condition: template
    value_template: '{{ trigger.to_state.state not in ["None", "unknown", "unavailable"]
      and trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: script.alexa_timer_announce
    data_template:
      duration: '{{ (as_timestamp(trigger.to_state.state) - now().timestamp() + 15)
        | timestamp_custom("%H:%M:%S", false) }}'
