########################################################
## CONFIG
########################################################
input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'

input_boolean:
  alexa_actionable_notification_simulate_responsenone:
    name: Alexa Actionable Notification simulate ResponseNone
    initial: off


########################################################
## SCRIPTS
########################################################
script:

###################
## Default actionable notification on any Echo device 
## https://github.com/keatontaylor/alexa-actions/wiki/FirstAction 
##
  activate_alexa_actionable_notification:
    description: 'Activate Alexa actionable notification'
    fields:
      text:
        description: 'The text you would like alexa to speak.'
      event_id:
        description: 'Correlation ID for event responses'
      alexa_device: 
        description: 'Alexa device you want to trigger'
    sequence:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.alexa_actionable_notification
          value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
      - service: media_player.play_media
        data_template:
          entity_id: "{{ alexa_device }}"
          media_content_type: skill
          media_content_id: amzn1.ask.skill.a93e6079-eda2-4b00-8f98-bf22d33014af

#  activate_alexa_actionable_notification_postpone:
#    alias: Front Door response no Echo Show kitchen
#    sequence:
#      - service: script.house_speech_kitchen
#        data_template:
#          tts_msg: "I'll check again later."

#  activate_alexa_actionable_notification_ignore:
#    alias: Front Door response none Echo Show kitchen
#    sequence:
#      - service: script.house_speech_kitchen
#        data_template:
#          tts_msg: "I did not detect a response. I'll ask again later."

########################################################
## AUTOMATIONS
########################################################
automation:
###################
## Lock unlocked for 5 minutes, trigger Alexa question
##
  - alias: Front door left unlocked for 5 mins
    trigger:
      platform: state
      entity_id: lock.conexis_l1
      to: 'unlocked'
      for:
        minutes: 5
    action:
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
      - service: script.activate_alexa_actionable_notification
        data_template:
          text: The front door has been unlocked for 5 minutes, would you like me to lock it?
          event_id: actionable_notification_lock_left_unlocked
          alexa_device: media_player.kitchen_echo_show
###################
## Lock unlocked for 15 minutes, trigger Alexa question
##
  - alias: Front door left unlocked for 15 mins
    trigger:
      platform: state
      entity_id: lock.conexis_l1
      to: 'unlocked'
      for:
        minutes: 15
    action:
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
      - service: script.activate_alexa_actionable_notification
        data_template:
          text: The front door has been unlocked for 15 minutes, would you like me to lock it?
          event_id: actionable_notification_lock_left_unlocked
          alexa_device: media_player.kitchen_echo_show
###################
## Lock unlocked for 60 minutes, trigger Alexa question
##
  - alias: Front door left unlocked for 60 mins
    trigger:
      platform: state
      entity_id: lock.conexis_l1
      to: 'unlocked'
      for:
        minutes: 60
    action:
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
      - service: script.activate_alexa_actionable_notification
        data_template:
          text: The front door has been unlocked for an hour, would you like me to lock it?
          event_id: actionable_notification_lock_left_unlocked
          alexa_device: media_player.kitchen_echo_show
###################
## Lock unlocked for 180 minutes, trigger Alexa question
##
  - alias: Front door left unlocked for 180 mins
    trigger:
      platform: state
      entity_id: lock.conexis_l1
      to: 'unlocked'
      for:
        minutes: 180
    action:
      # - service: input_boolean.turn_on
      #   entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
      - service: script.activate_alexa_actionable_notification
        data_template:
          text: The front door has been unlocked for three hours now, would you like me to lock it?
          event_id: actionable_notification_lock_left_unlocked
          alexa_device: media_player.kitchen_echo_show

###################
## Lock after 'Yes' response
##
  - alias: Lock the door via actionable notification
    trigger:
      platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_lock_left_unlocked
        event_response: ResponseYes
    action:
#      - service: input_boolean.turn_off
 #       entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
      - service: lock.lock
        entity_id: lock.conexis_l1
###################
## Try again much later after 'No' response
##
#  - alias: Try again much later via actionable notification
#    trigger:
#      platform: event
#      event_type: alexa_actionable_notification
#      event_data:
#        event_id: actionable_notification_lock_left_unlocked
#        event_response: ResponseNo
#    action:
#      - service: input_boolean.turn_off
#        entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
#      - service: script.turn_on
#        entity_id: script.activate_alexa_actionable_notification_postpone

###################
## Try again later if ignored
## This isn't working, ResponseNone is unreliable - see https://github.com/keatontaylor/alexa-actions/issues/17
##
#  - alias: Try again later via actionable notification
#    trigger:
#      platform: event
#      event_type: alexa_actionable_notification
#      event_data:
#        event_id: actionable_notification_lock_left_unlocked
#        event_response: ResponseNone
#    action:
#      - service: script.house_alert_downstairs
#        data_template:
#          tts_msg: "I did not detect a response. I'll ask again later."

###################
## Simulate ResponseNone
## Takes approx 5 seconds for Actionable Notification to start, 3-4 seconds to speak the question, wait for 6 seconds
#  - alias: No response for 15 seconds
#    trigger:
#      platform: state
#      entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
#      to: 'on'
#      for:
#        seconds: 15
#    action:
#      - service: input_boolean.turn_off
#        entity_id: input_boolean.alexa_actionable_notification_simulate_responsenone
#      - service: script.house_speech_kitchen
#        data_template:
#          tts_msg: "I did not detect a response. I'll ask again later."

