########################################################
## CONFIG
########################################################
input_boolean:

########################################################
## SWITCHES
########################################################
switch:

########################################################
## SCRIPTS
########################################################
script:

  denon_avr_info:
    alias: Denon AVR onscreen channel info
    sequence:
    - service: denonavr.get_command
      data:
        command: /goform/formiPhoneAppDirect.xml?RCSHP0230031
      target:
        entity_id: media_player.denon_avr_x3600h


########################################################
## AUTOMATIONS
########################################################
automation:
