########################################################
## CONFIG
########################################################
input_boolean:
###################
## Random lights, for map
##
  random_light_living_room_floor:
    name: Rainbow - xiaomi gateway
    icon: mdi:looks
  random_light_living_room_sofa:
    name: Rainbow - sofa backlight
    icon: mdi:looks
  random_light_reading_light:
    name: Rainbow - reading light
    icon: mdi:looks
  random_light_dining_room:
    name: Rainbow - dining room
    icon: mdi:looks
  random_light_dining_room_wall_wash:
    name: Rainbow - dining wall wash
    icon: mdi:looks

########################################################
## SWITCHES
########################################################
switch:

########################################################
## SCRIPTS
########################################################
script:

  ########################################################
  ########      Rainbow effects                   ########
  ########################################################
  ##
  ## Living room floor
  ##
  random_light_living_room_floor:
    alias: Random light living room floor
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_living_room_floor_loop
      - condition: state
        entity_id: input_boolean.random_light_living_room_floor
        state: 'on'
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_04cf8c8fa2af
          brightness: 254
      - service: light.turn_on
        entity_id: light.gateway_light_04cf8c8fa2af
        data_template:
          hs_color:
            - "{{ (30 + (state_attr('light.gateway_light_04cf8c8fa2af', 'hs_color')[0] or 0)) % 360 }}"
            - 100
          brightness: 255
          transition: 3
      - service: script.random_light_living_room_floor_loop
  random_light_living_room_floor_loop:
    alias: Random light living room floor loop
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_living_room_floor
      - condition: state
        entity_id: input_boolean.random_light_living_room_floor
        state: 'on'
      - delay:
          seconds: 6
      - service: script.random_light_living_room_floor
  ##
  ##### Living room sofa
  ##
  random_light_living_room_sofa:
    alias: Random light living room sofa
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_living_room_sofa_loop
      - condition: state
        entity_id: input_boolean.random_light_living_room_sofa
        state: 'on'
      - service: light.turn_on
        data:
          entity_id: light.living_room_sofa
          brightness: 254
      - service: light.turn_on
        entity_id: light.living_room_sofa
        data_template:
          hs_color:
            - "{{ (30 + (state_attr('light.living_room_sofa', 'hs_color')[0] or 0)) % 360 }}"
            - 100
          brightness: 255
          transition: 3
      - service: script.random_light_living_room_sofa_loop
  random_light_living_room_sofa_loop:
    alias: Random light living room sofa loop
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_living_room_sofa
      - condition: state
        entity_id: input_boolean.random_light_living_room_sofa
        state: 'on'
      - delay:
          seconds: 9
      - service: script.random_light_living_room_sofa
  ##
  ##### Reading light
  ##
  random_light_reading_light:
    alias: Random light reading light
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_reading_light_loop
      - condition: state
        entity_id: input_boolean.random_light_reading_light
        state: 'on'
      - service: light.turn_on
        data:
          entity_id: light.reading_light
          brightness: 140
      - service: light.turn_on
        entity_id: light.reading_light
        data_template:
          hs_color:
            - "{{ (30 + (state_attr('light.reading_light', 'hs_color')[0] or 0)) % 360 }}"
            - 100
          brightness: 190
          transition: 3
      - service: script.random_light_reading_light_loop
  random_light_reading_light_loop:
    alias: Random light reading light loop
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_reading_light
      - condition: state
        entity_id: input_boolean.random_light_reading_light
        state: 'on'
      - delay:
          seconds: 9
      - service: script.random_light_reading_light
  ##
  ##### Dining room
  ##
  random_light_dining_room:
    alias: Random light dining room
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_dining_room_loop
      - condition: state
        entity_id: input_boolean.random_light_dining_room
        state: 'on'
      - service: light.turn_on
        data:
          entity_id: light.dining_room
          brightness: 254
      - service: light.turn_on
        entity_id: light.dining_room
        data_template:
          hs_color:
            - "{{ (30 + (state_attr('light.dining_room', 'hs_color')[0] or 0)) % 360 }}"
            - 100
          transition: 3
      - service: script.random_light_dining_room_loop
  random_light_dining_room_loop:
    alias: Random light dining room loop
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_dining_room
      - condition: state
        entity_id: input_boolean.random_light_dining_room
        state: 'on'
      - delay:
          seconds: 9
      - service: script.random_light_dining_room
  ##
  ##### Dining room wall wash
  ## 
  random_light_dining_wall_wash:
    alias: Random light dining wall wash
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_dining_wall_wash_loop
      - condition: state
        entity_id: input_boolean.random_light_dining_room_wall_wash
        state: 'on'
      - service: light.turn_on
        data:
          entity_id: light.hue_color_candle_1
          brightness: 254
      - service: light.turn_on
        entity_id: light.hue_color_candle_1
        data_template:
          hs_color:
            - "{{ (30 + (state_attr('light.hue_color_candle_1', 'hs_color')[0] or 0)) % 360 }}"
            - 100
          transition: 3
      - service: script.random_light_dining_wall_wash_loop
  random_light_dining_wall_wash_loop:
    alias: Random light dining wall wash loop
    sequence:
      - service: script.turn_off
        entity_id: script.random_light_dining_wall_wash
      - condition: state
        entity_id: input_boolean.random_light_dining_room_wall_wash
        state: 'on'
      - delay:
          seconds: 9
      - service: script.random_light_dining_wall_wash
    
  ########################################################
  ## Rainbow effects for RGB non-XY lights (e.g. Lohas)  ########
  ########################################################
  ##
  ## Choose a light
  ##
  #dining_room_wall_wash_rainbow_effect:
  #  alias: Dining Room wall wash rainbow effect
  #  sequence:
  #    - service: script.turn_off
  #      entity_id: script.dining_room_wall_wash_light_loop
  #    - service: script.preprocess_color
  #      data:
  #        id: light.10245283dc4f22b60919
  ###
  ### Choose random colour
  ###
  #preprocess_color:
  #  sequence:
  #    - service: script.set_color
  #      data_template:
  #        id: '{{ id }}'
  #        colors: >-
  #          {%- set h = (now().second|int)/60 %}
  #          {%- set s = 1.0 %}
  #          {%- set v = 1.0 %}
  #          {%- set i = (h * 6)|int %}
  #          {%- set f = h * 6 - i %}
  #          {%- set p = v * (1 - s) %}
  #          {%- set q = v * (1 - f * s) %}
  #          {%- set t = v * (1 - (1 - f) * s) %}
  #          {%- if i % 6 == 0 %}
  #            {% set r = v %}
  #            {% set g = t %}
  #            {% set b = p %}
  #          {%- elif i % 6 == 1 %}
  #            {% set r = q %}
  #            {% set g = v %}
  #            {% set b = p %}
  #          {%- elif i % 6 == 2 %}
  #            {% set r = p %}
  #            {% set g = v %}
  #            {% set b = t %}
  #          {%- elif i % 6 == 3 %}
  #            {% set r = p %}
  #            {% set g = q %}
  #            {% set b = v %}
  #          {%- elif i % 6 == 4 %}
  #            {% set r = t %}
  #            {% set g = p %}
  #            {% set b = v %}
  #          {%- elif i % 6 == 5 %}
  #            {% set r = v %}
  #            {% set g = p %}
  #            {% set b = q %}
  #          {%- endif %}
  #          {{ (255*r)|round(0) }}, {{ (255*g)|round(0) }}, {{ (255*b)|round(0) }}, {{ (360*h)|int }}
  #        transition: 3
  ###
  ### Set the colour
  ###
  #set_color:
  #  sequence:
  #    - service: light.turn_on
  #      data_template:
  #        entity_id: '{{ id }}'
  #        rgb_color: [ "{{ colors.split(',')[0]|int }}", "{{ colors.split(',')[1]|int }}", "{{ colors.split(',')[2]|int }}" ]
  #        transition: "{{ transition|float }}"
  #    - service: script.turn_on
  #      entity_id: script.dining_room_wall_wash_light_loop
  #        
  #
  #dining_room_wall_wash_light_loop:
  #  alias: Dining room wall wash light loop
  #  sequence:
  #    - service: script.turn_off
  #      entity_id: script.dining_room_wall_wash_rainbow_effect
  #    - condition: state
  #      entity_id: input_boolean.random_light_dining_room_wall_wash
  #      state: 'on'
  #    - delay:
  #        seconds: 30
  #    - service: script.turn_on
  #      entity_id: script.dining_room_wall_wash_rainbow_effect
  
  

########################################################
## AUTOMATIONS
########################################################
automation:
##############################################################################
######## Sync random input_booleans if lights turned off elsewhere #########
######## Also turning off light turns off random effect script       #########
##############################################################################
  - alias: Turn off light switch input_booleans
    trigger:
      - platform: state
        entity_id: light.living_room_sofa
        to: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: 
            - input_boolean.random_light_living_room_sofa
  - alias: Turn off light switch input_booleans 2
    trigger:
      - platform: state
        entity_id: light.reading_light
        to: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: 
            - input_boolean.random_light_reading_light
  - alias: Turn off light switch input_booleans 3
    trigger:
      - platform: state
        entity_id: light.dining_room
        to: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: 
            - input_boolean.random_light_dining_room
  - alias: Turn off light switch input_booleans 4
    trigger:
      - platform: state
        entity_id: light.gateway_light_04cf8c8fa2af
        to: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: 
            - input_boolean.random_light_living_room_floor
  - alias: Turn off light switch input_booleans 5
    trigger:
      - platform: state
        entity_id: light.hue_color_candle_1
        to: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: 
            - input_boolean.random_light_dining_room_wall_wash

  ###############################################################
  # Random light living room floor (with matching script)
  ###############################################################
  - alias: Random light living room floor
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_living_room_floor
        to: "on"
    action:
      - service: script.random_light_living_room_floor

  - alias: Random light living room floor off
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_living_room_floor
        to: "off"
    action:
      - service: script.turn_off
        entity_id: script.random_light_living_room_floor

  ###############################################################
  # Random light living room sofa (with matching script)
  ###############################################################
  - alias: Random light living room sofa
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_living_room_sofa
        to: "on"
    action:
      - service: script.random_light_living_room_sofa

  - alias: Random light living room sofa off
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_living_room_sofa
        to: "off"
    action:
      - service: script.turn_off
        entity_id: script.random_light_living_room_sofa

  ###############################################################
  # Random light reading light (with matching script)
  ###############################################################
  - alias: Random light reading light
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_reading_light
        to: "on"
    action:
      - service: script.random_light_reading_light

  - alias: Random light reading light off
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_reading_light
        to: "off"
    action:
      - service: script.turn_off
        entity_id: script.random_light_reading_light


  ###############################################################
  # Random light dining room (with matching script)
  ###############################################################
  - alias: Random light dining room
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_dining_room
        to: "on"
    action:
      - service: script.random_light_dining_room

  - alias: Random light dining room off
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_dining_room
        to: "off"
    action:
      - service: script.turn_off
        entity_id: script.random_light_dining_room

  ###############################################################
  # Random light dining room wall wash (with matching script)
  ###############################################################
  - alias: Random light dining room wall wash
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_dining_room_wall_wash
        to: "on"
    action:
      - service: script.turn_on
        entity_id: script.random_light_dining_wall_wash

  - alias: Random light dining room wall wash off
    trigger:
      - platform: state
        entity_id: input_boolean.random_light_dining_room_wall_wash
        to: "off"
    action:
      - service: script.turn_off
        entity_id: script.random_light_dining_wall_wash

