########################################################
## CONFIG
########################################################

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_token
    url: https://thoughton.duckdns.org
    trusted_networks:
      # see https://core.telegram.org/bots/webhooks#how-do-i-check-for-open-ports-or-limit-access-to-my-bot
      - 149.154.160.0/20 
      - 91.108.4.0/22
      - 172.30.33.6 # the IP I see being denied in my hassio logs when I press the telegram button
      - 192.168.0.81 # my local hassio, running nginx
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
# notify.telegram_timhiphonex
  - name: telegram_timhiphonex
    platform: telegram
    chat_id: !secret telegram_chat_id
    
########################################################
## SENSORS
########################################################
sensor:


########################################################
## SCRIPTS
########################################################
script:

###################
## telegram example
## https://community.home-assistant.io/t/telegram-bot-notifications-and-communication/50247/134
##
  telegram_example:
    alias: Telegram example
    sequence:
    - service: notify.telegram_timhiphonex
      data:
        title: '*Send a message*'
        message: "That's an example that _sends_ a *formatted* message with a custom inline keyboard."
        data:
          inline_keyboard:
            - 'Option 1:/button1, Option 2:/button2, Option 3:/button3'
            - 'Option 4:/button4'


########################################################
## AUTOMATIONS
########################################################
automation:

###################
## response to button one
##
  - alias: 'Telegram callback BUTTON ONE'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/button1'
    action:
    # acknowledgement message
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Okay. Button one pressed.'
    # remove keyboard
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: !secret telegram_chat_id
        inline_keyboard: []
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "Button one pressed"

###################
## response to button two
##
  - alias: 'Telegram callback BUTTON TWO'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/button2'
    action:
    # acknowledgement message
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Okay. Button two pressed.'
    # remove keyboard
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: !secret telegram_chat_id
        inline_keyboard: []
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "Button two pressed"

###################
## response to button three
##
  - alias: 'Telegram callback BUTTON THREE'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/button3'
    action:
    # acknowledgement message
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Okay. Button three pressed.'
    # remove keyboard
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: !secret telegram_chat_id
        inline_keyboard: []
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "Button three pressed"
        
###################
## response to button four
##
  - alias: 'Telegram callback BUTTON FOUR'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/button4'
    action:
    # acknowledgement message
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Okay. Button four pressed.'
    # remove keyboard
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: !secret telegram_chat_id
        inline_keyboard: []
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "Button four pressed"

##
## command line example
## curl -s "https://api.telegram.org/bot$KEY/sendMessage?chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT"
##