########################################################
## CONFIG
########################################################
input_boolean:
###################
## Vacuum booleans for lovelace feed & map to trigger scripts
## (Doing it this way so icon on map goes green while cleaning taking place)
##
  vacuum_robomop_house:
    name: Starting house vacuum
    initial: off
    icon: mdi:robot-vacuum
  vacuum_robomop_office:
    name: Starting office vacuum
    initial: off
    icon: mdi:robot-vacuum
  vacuum_robomop_dining_room:
    name: Starting dining room vacuum
    initial: off
    icon: mdi:robot-vacuum
  vacuum_robomop_kitchen:
    name: Starting kitchen vacuum
    initial: off
    icon: mdi:robot-vacuum
  vacuum_robomop_living_room:
    name: Starting living room vacuum
    initial: off
    icon: mdi:robot-vacuum


########################################################
## SENSORS
########################################################
sensor:
  - platform: template
    sensors:
      #
      # sensors
      #
      xiaomi_robomop_status:
        friendly_name: "Xiaomi RoboMop status"
        value_template: "{{ (state_attr('vacuum.robomop', 'status')) }}"
      xiaomi_robomop_water_grade:
        friendly_name: "Xiaomi RoboMop water grade"
        value_template: "{{ (state_attr('vacuum.robomop', 'water_grade')) }}"
      xiaomi_robomop_suction_grade:
        friendly_name: "Xiaomi RoboMop suction grade"
        value_template: "{{ (state_attr('vacuum.robomop', 'suction_grade')) }}"
      #
      # status icon
      #
      vacuum_robomop_status:
        friendly_name: Status
        value_template: 'Status: {{ states.vacuum.robomop.attributes.status }}'
        icon_template: >
          {% set val =  states.vacuum.robomop.attributes.status  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}


########################################################
## SCRIPTS
########################################################
script:


###################
## Vacuum stuck announcement
##
  vacuum_robomop_timer_announce:
    sequence:
      - condition: state
        entity_id: vacuum.robomop
        state: 'error'
      - service: script.house_announce_echos
        data_template:
          tts_msg: "The Robot Vacuum is stuck! Release it and press the resume button."
      - service: script.turn_on
        entity_id: script.vacuum_robomop_timer_loop

  vacuum_robomop_timer_loop:
    sequence:
      - condition: state
        entity_id: vacuum.robomop
        state: 'error'
      - delay: "00:00:15"
      - service: script.turn_on
        entity_id: script.vacuum_robomop_loop_intermediate

  # Need third step to avoid 'Script already running' error after 2nd loop
  vacuum_robomop_loop_intermediate:
    sequence:
      - condition: state
        entity_id: vacuum.robomop
        state: 'error'
      - delay: "00:00:15"
      - service: script.turn_on
        entity_id: script.vacuum_robomop_timer_announce

###################
## Vacuum commands
##
  vacuum_robomop_house:
      alias: "Vacuum the House"
      sequence:
        - service: vacuum.send_command
          data:
            entity_id: vacuum.robomop
            command: app_zoned_clean
            params: [[23980,27580,26430,24140,1],[23760,24000,27200,21080,1],[26620,25230,29720,21580,1],[27350,21420,29300,15080,1],[23560,20910,26820,15030,1]]
#        - service: homeassistant.turn_off
#          data:
#            entity_id: input_boolean.vacuum_robomop_office
#        - service: homeassistant.turn_on
#          data:
#            entity_id: input_boolean.vacuum_robomop_office
  vacuum_robomop_office:
      alias: "Vacuum the Office"
      sequence:
        - service: vacuum.send_command
          data:
            entity_id: vacuum.robomop
            command: app_zoned_clean
            params: [[23980,27580,26430,24140,1]]
#        - service: homeassistant.turn_off
#          data:
#            entity_id: input_boolean.vacuum_robomop_office
#        - service: homeassistant.turn_on
#          data:
#            entity_id: input_boolean.vacuum_robomop_office
  vacuum_robomop_dining_room:
      alias: "Vacuum the Dining Room"
      sequence:
        - service: vacuum.send_command
          data:
            entity_id: vacuum.robomop
            command: app_zoned_clean
            params: [[23760,24000,27200,21080,1],[26620,25230,29720,21580,1]]
#        - service: homeassistant.turn_off
#          data:
#            entity_id: input_boolean.vacuum_robomop_dining_room
#        - service: homeassistant.turn_on
#          data:
#            entity_id: input_boolean.vacuum_robomop_dining_room
  vacuum_robomop_kitchen:
      alias: "Vacuum the Kitchen"
      sequence:
        - service: vacuum.send_command
          data:
            entity_id: vacuum.robomop
            command: app_zoned_clean
            params: [[27350,21420,29300,15080,1]]
#        - service: homeassistant.turn_off
#          data:
#            entity_id: input_boolean.vacuum_robomop_kitchen
#        - service: homeassistant.turn_on
#          data:
#            entity_id: input_boolean.vacuum_robomop_kitchen
  vacuum_robomop_office_and_kitchen:
      alias: "robomop Clean before bed"
      sequence:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - sun
        - condition: state
          entity_id: device_tracker.paulus
          state: 'home'
        - service: vacuum.send_command
          data:
            entity_id: vacuum.robomop
            command: app_zoned_clean
            params: [[23980,27580,26430,24140,1],[27350,21420,29300,15080,1]]
#        - service: homeassistant.turn_off
#          data:
#            entity_id: input_boolean.vacuum_robomop_office
#        - service: homeassistant.turn_on
#          data:
#            entity_id: input_boolean.vacuum_robomop_office
  vacuum_robomop_living_room:
      alias: "Vacuum the Living Room"
      sequence:
        - service: vacuum.send_command
          data:
            entity_id: vacuum.robomop
            command: app_zoned_clean
            params: [[23560,20910,26820,15030,1]]
#        - service: homeassistant.turn_off
#          data:
#            entity_id: input_boolean.vacuum_robomop_living_room
#        - service: homeassistant.turn_on
#          data:
#            entity_id: input_boolean.vacuum_robomop_living_room
  vacuum_robomop_pause:
      alias: "Pause the Vacuum"
      sequence:
        - service: vacuum.stop
          data:
            entity_id: vacuum.robomop
  vacuum_robomop_stop:
      alias: "Stop the Vacuum"
      sequence:
        - service: vacuum.stop
          data:
            entity_id: vacuum.robomop
  vacuum_robomop_resume:
      alias: "Continue Vacuuming"
      sequence:
        - service: vacuum.start
          data:
            entity_id: vacuum.robomop
  vacuum_robomop_start:
      alias: "Start the Vacuum"
      sequence:
        - service: vacuum.start
          data:
            entity_id: vacuum.robomop
  vacuum_robomop_cancel:
      alias: "Cancel the Vacuum"
      sequence:
        - service: vacuum.stop
          data:
            entity_id: vacuum.robomop
        - delay: '00:00:02'
        - service: vacuum.return_to_base
          data:
            entity_id: vacuum.robomop
  vacuum_robomop_dock:
      alias: "Dock the Vacuum"
      sequence:
        - service: vacuum.stop
          data:
            entity_id: vacuum.robomop
        - delay: '00:00:02'
        - service: vacuum.return_to_base
          data:
            entity_id: vacuum.robomop
  vacuum_robomop_where:
      alias: "Where is the Vacuum"
      sequence:
        - service: vacuum.locate
          data:
            entity_id: vacuum.robomop
  vacuum_robomop_locate:
      alias: "Locate the Vacuum"
      sequence:
        - service: vacuum.locate
          data:
            entity_id: vacuum.robomop

###################
## Vacuum aliases (for Homekit/Alexa etc)
##
  clean_house:
      alias: Clean the House
      sequence:
        - service: script.turn_on
          entity_id: script.vacuum_robomop_house
  clean_office:
      alias: Clean the Office
      sequence:
        - service: script.turn_on
          entity_id: script.vacuum_robomop_office
  clean_dining_room:
      alias: Clean the Dining Room
      sequence:
        - service: script.turn_on
          entity_id: script.vacuum_robomop_dining_room
  clean_kitchen:
      alias: Clean the Kitchen
      sequence:
        - service: script.turn_on
          entity_id: script.vacuum_robomop_kitchen
  clean_living_room:
      alias: Clean the Living Room
      sequence:
        - service: script.turn_on
          entity_id: script.vacuum_robomop_living_room

########################################################
## AUTOMATIONS
########################################################
automation:

###################
## robomop error
##
  - alias: "robomop needs help"
    trigger:
      - platform: state
        entity_id: vacuum.robomop
        from: 'cleaning'
        to: 'error'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_timer_announce
      
###################
## robomop finished
##
  - alias: "robomop finished zone cleaning"
    trigger:
      - platform: state
        entity_id: vacuum.robomop
        from: 'returning'
        to: 'docked'
    action:
      - service: homeassistant.turn_off
        entity_id: 
          - input_boolean.vacuum_robomop_house
          - input_boolean.vacuum_robomop_office
          - input_boolean.vacuum_robomop_dining_room
          - input_boolean.vacuum_robomop_kitchen
          - input_boolean.vacuum_robomop_living_room
      
###################
## Input boolean trigger Clean house 
## 
  - alias: "Input Boolean start cleaning house"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_house
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_house
###################
## Input boolean trigger Clean office 
## 
  - alias: "Input Boolean start cleaning office"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_office
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_office
###################
## Input boolean trigger Clean dining room 
## 
  - alias: "Input Boolean start cleaning dining room"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_dining_room
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_dining_room
###################
## Input boolean trigger Clean kitchen 
## 
  - alias: "Input Boolean start cleaning kitchen"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_kitchen
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_kitchen
###################
## Input boolean trigger Clean living room 
## 
  - alias: "Input Boolean start cleaning living room"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_living_room
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_living_room
      
      
###################
## Input boolean trigger Clean house off
## 
  - alias: "Input Boolean start cleaning office off"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_house
        to: 'off'
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: vacuum.robomop
            state: 'docked'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_dock
###################
## Input boolean trigger Clean office off
## 
  - alias: "Input Boolean start cleaning office off"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_office
        to: 'off'
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: vacuum.robomop
            state: 'docked'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_dock
###################
## Input boolean trigger Clean dining room off
## 
  - alias: "Input Boolean start cleaning dining room off"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_dining_room
        to: 'off'
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: vacuum.robomop
            state: 'docked'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_dock
###################
## Input boolean trigger Clean kitchen off
## 
  - alias: "Input Boolean start cleaning kitchen off"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_kitchen
        to: 'off'
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: vacuum.robomop
            state: 'docked'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_dock
###################
## Input boolean trigger Clean living room off
## 
  - alias: "Input Boolean start cleaning living room off"
    trigger:
      - platform: state
        entity_id: input_boolean.vacuum_robomop_living_room
        to: 'off'
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: vacuum.robomop
            state: 'docked'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_robomop_dock
      
      