########################################################
## CONFIG
########################################################
input_boolean:
  washingmachine_needs_emptying:
    name: Washer dryer needs emptying
  washingmachine_status_enquiry:
    name: Washer dryer status enquiry
  washingmachine_finished:
    name: Washer dryer finished
  washingmachine_running:
    name: Washer dryer running


########################################################
## SENSORS
########################################################
sensor:
  - platform: template
    sensors:
      #
      # Washer dryer status sensor
      #
      washer_dryer_state:
        friendly_name: "Washer dryer state"
        value_template: >-
          {% if states.switch.washer_dryer_energy_monitor.state == "off" %}
            Switched off
          {% else %}
              {% if states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 1  %}
                Standby
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 10 %}
                Idle
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 35 %}
                Filling / Draining
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 60 %}
                Tumbling
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 110 %}
                Tumbling and draining
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 150 %}
                Washing
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 200 %}
                Spinning
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 500 %}
                High Speed Spinning
              {% elif states.sensor.washer_dryer_energy_monitor_current_consumption.state|float(0) < 1800 %}
                Spin drying
              {% else %}
                Error
              {% endif %}
          {% endif %}



########################################################
## SCRIPTS
########################################################
script:

###################
## Washer dryer not emptied loop, actionable notifications
##
  washer_dryer_needs_emptying_loop:
    sequence:
      - condition: state
        entity_id: input_boolean.washingmachine_needs_emptying
        state: "on"
      - delay: "00:00:05"
      - service: notify.mobile_app_timh_iphonex256
        data:
          title: "Laundry alert!"
          message: "The washer dryer needs emptying."
          data:
            actions:
              # Don't forget to 'Update push settings' on the iOS app!
              - identifier: 'WASHER_DRYER_EMPTYING_1'
                title: "Later."
                activationMode: 'background'
                authenticationRequired: true
                destructive: false
                behavior: 'default'
              - identifier: 'WASHER_DRYER_EMPTYING_2'
                title: "I've emptied it."
                activationMode: 'background'
                authenticationRequired: true
                destructive: true
                behavior: 'default'
            push:
      - service: script.house_announce_downstairs
        data_template:
          notification_feed_name: WasherDryer
          tts_msg: "The washer dryer has finished. Please take out the laundry."
      - service: script.turn_on
        entity_id: script.washer_dryer_needs_emptying_loop_intermediate

  # Need third step to avoid 'Script script.washer_dryer_needs_emptying_loop already running' error after 2nd loop
  washer_dryer_needs_emptying_loop_intermediate:
    sequence:
      - delay: "00:00:15"
      - service: script.turn_on
        entity_id: script.washer_dryer_needs_emptying_loop_final
    
  washer_dryer_needs_emptying_loop_final:
    sequence:
      - delay: "00:10:00"
      - service: script.turn_on
        entity_id: script.washer_dryer_needs_emptying_loop


########################################################
#####  Washing machine remote start  ########
########################################################
  washing_machine_remote_start_routine:
    alias: Washing machine remote start routine
    sequence:
    - service: homeassistant.turn_on
      target:
        entity_id: script.washing_machine_wake_up
    - delay: 2
    - service: homeassistant.turn_on
      target:
        entity_id: script.washing_machine_remote_start
  washing_machine_wake_up:
    alias: Washing machine wake up
    sequence:
    - condition: and
      conditions:
        # Check machine is sleeping, if machine is awake the wake_up command will turn it off and cancel remote start!
        - condition: or
          conditions:
            # machine is in standby
            - condition: state
              entity_id: sensor.washer_dryer_run_state
              state: 'Standby'
            # machine is sleeping
            - condition: state
              entity_id: sensor.washer_dryer_run_state
              state: '-'
        # Check remote start is on (NB this stays on for entire cycle)
        - condition: state
          entity_id: binary_sensor.washer_dryer_remote_start
          state: "on"
    - service: smartthinq_sensors.wake_up
      data: {}
      target:
        device_id: e04749fec3959aa54410311d2d48a946
  washing_machine_remote_start:
    alias: Washing machine remote start
    sequence:
    - service: smartthinq_sensors.remote_start
      data: {}
      target:
        device_id: e04749fec3959aa54410311d2d48a946

########################################################
## AUTOMATIONS
########################################################
automation:

  - alias: LG Washing machine remote start when sunny
    trigger:
      platform: time_pattern
      minutes: '/2'
    condition:
      condition: and
      conditions:
        # Check remote start is on (NB this stays on for entire cycle)
        - condition: state
          entity_id: binary_sensor.washer_dryer_remote_start
          state: "on"
        # solar panels are generating
        - condition: numeric_state
          entity_id: sensor.inverter_instant_power
          above: 1000
        - condition: or
          conditions:
            # machine is in standby
            - condition: state
              entity_id: sensor.washer_dryer_run_state
              state: 'Standby'
            # machine is sleeping
            - condition: state
              entity_id: sensor.washer_dryer_run_state
              state: '-'
    action:
      - service: homeassistant.turn_on
        entity_id: script.washing_machine_remote_start_routine
      - service: script.house_announce_downstairs
        data_template:
          notification_feed_name: WashingMachine
          tts_msg: "Solar power generation in excess of one kilowatt, initiating washing machine routine."
          
          


  - alias: LG Washing machine starting
    trigger:
    - platform: state
      entity_id: sensor.washer_dryer_run_state
      to: "Washing"
    action:
    # turn off boolean if starting a new load
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.washingmachine_needs_emptying
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.washingmachine_status_enquiry

###################
## Washer Dryer - test state, detect if finished
##
  # - alias: Action - Set washing machine to running
  #   trigger:
  #   - platform: numeric_state
  #     entity_id: sensor.washer_dryer_energy_monitor_current_consumption
  #     above: '6'
  #     for:
  #       minutes: 5
  #   condition: []
  #   action:
  #   - service: input_select.select_option
  #     data:
  #       entity_id: input_select.washingmachine_status
  #       option: "Running"
  #   # turn off boolean if starting a new load
  #   - service: homeassistant.turn_off
  #     data:
  #       entity_id: input_boolean.washingmachine_needs_emptying
  #   - service: homeassistant.turn_off
  #     data:
  #       entity_id: input_boolean.washingmachine_status_enquiry

  # - alias: Action - Set washing machine as finished
  #   trigger:
  #   - platform: numeric_state
  #     entity_id: sensor.washer_dryer_energy_monitor_current_consumption
  #     below: '10'
  #     for:
  #       minutes: 7
  #   condition:
  #   - condition: state
  #     entity_id: input_select.washingmachine_status
  #     state: "Running"
  #   action:
  #   - service: input_select.select_option
  #     data:
  #       entity_id: input_select.washingmachine_status
  #       option: "Finished"


# Finished, start notification loop, set status to off
  # - alias: Notify - Washing machine finished
  #   trigger:
  #   - platform: state
  #     entity_id: input_select.washingmachine_status
  #     to: "Finished"
  #   action:
  #   - service: homeassistant.turn_on
  #     data:
  #       entity_id: input_boolean.washingmachine_needs_emptying
  #   - service: homeassistant.turn_on
  #     entity_id: script.washer_dryer_needs_emptying_loop
  #   - service: input_select.select_option
  #     data:
  #       entity_id: input_select.washingmachine_status
  #       option: "Powered Off"

# Finished, from LG integration
  - alias: LG Washing machine finished
    trigger:
    - platform: state
      entity_id: sensor.washer_dryer_run_state
      to: "Finished"
    action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.washingmachine_needs_emptying
    - service: homeassistant.turn_on
      entity_id: script.washer_dryer_needs_emptying_loop

###################
## Washer dryer report status
##
  - alias: Emptied the washing machine
    trigger:
    - platform: state
      entity_id: input_boolean.washingmachine_status_enquiry
      to: "on"
    action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.washingmachine_needs_emptying
    - service: script.house_announce_downstairs
      data_template:
        notification_feed_name: WasherDryer
        tts_msg: "Washing machine status update acknowledged."
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.washingmachine_status_enquiry

###################
## Triggers for iOS responses
##
  - alias: Washer dryer notification response 1
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHER_DRYER_EMPTYING_1
    action:
      - service: script.house_announce_downstairs
        data_template:
          notification_feed_name: WasherDryer
          tts_msg: "Okay, I'll remind you in ten minutes."
  # Flip the input_boolean, end the message loop
  - alias: Washer dryer notification response 2
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHER_DRYER_EMPTYING_2
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.washingmachine_status_enquiry
      - service: script.house_announce_downstairs
        data_template:
          notification_feed_name: WasherDryer
          tts_msg: "Okay, I'll stop reminding you."
