########################################################
## CONFIG
########################################################
input_boolean:
  washingmachine_needs_emptying:
    name: Washer dryer needs emptying
  washingmachine_status_enquiry:
    name: Washer dryer status enquiry
  washingmachine_finished:
    name: Washer dryer finished
  washingmachine_running:
    name: Washer dryer running


########################################################
## SENSORS
########################################################
sensor:
  - platform: template
    sensors:
      #
      # Washer dryer status sensor
      #
      washer_dryer_state:
        friendly_name: "Washer dryer state"
        value_template: >-
          {% if states.sensor.washer_dryer_energy_monitor.state == "off" %}
            Switched off
          {% else %}
              {% if states.sensor.washer_dryer_energy_monitor_watts.state|float < 1  %}
                Standby
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 10 %}
                Idle
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 35 %}
                Filling / Draining
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 60 %}
                Tumbling
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 110 %}
                Tumbling and draining
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 150 %}
                Washing
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 200 %}
                Spinning
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 500 %}
                High Speed Spinning
              {% elif states.sensor.washer_dryer_energy_monitor_watts.state|float < 1800 %}
                Spin drying
              {% else %}
                Error
              {% endif %}
          {% endif %}
      #
      # Washer dryer energy monitor
      #
      washer_dryer_energy_monitor_amps:
        friendly_name: "Current Amperage"
        value_template: '{{ states.switch.washer_dryer_energy_monitor.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      washer_dryer_energy_monitor_watts:
        friendly_name: "Current Wattage"
        value_template: '{{ states.switch.washer_dryer_energy_monitor.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      washer_dryer_energy_monitor_kw:
        friendly_name: "Total Energy"
        value_template: '{{ states.switch.washer_dryer_energy_monitor.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'
      washer_dryer_energy_monitor_kw_today:
        friendly_name: "Today's Energy"
        value_template: '{{ states.switch.washer_dryer_energy_monitor.attributes["today_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'      
      washer_dryer_energy_monitor_volts:
        friendly_name: "Current Voltage"
        value_template: '{{ states.switch.washer_dryer_energy_monitor.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'


########################################################
## SCRIPTS
########################################################
script:

###################
## Washer dryer not emptied loop, actionable notifications
##
  washer_dryer_needs_emptying_loop:
    sequence:
      - condition: state
        entity_id: input_boolean.washingmachine_needs_emptying
        state: "on"
      - delay: "00:00:05"
      - service: notify.mobile_app_timh_iphonex
        data:
          title: "Laundry alert!"
          message: "The washer dryer needs emptying."
          data:
            push:
              badge: 1
              category: "washerdryeremptying"
              # Don't forget to 'Update push settings' on the iOS app!
      - service: script.house_announce_echos
        data_template:
          tts_msg: "The washer dryer has finished. Please take out the laundry."
      - service: script.washer_dryer_needs_emptying_loop_intermediate

  # Need third step to avoid 'Script script.washer_dryer_needs_emptying_loop already running' error after 2nd loop
  washer_dryer_needs_emptying_loop_intermediate:
    sequence:
      - delay: "00:00:15"
      - service: script.washer_dryer_needs_emptying_loop_final
    
  washer_dryer_needs_emptying_loop_final:
    sequence:
      - delay: "00:10:00"
      - service: script.washer_dryer_needs_emptying_loop


########################################################
## AUTOMATIONS
########################################################
automation:
###################
## Washer Dryer - test state, detect if finished
##
  - alias: Action - Set washing machine to running
    trigger:
    - platform: numeric_state
      entity_id: sensor.washer_dryer_energy_monitor_watts
      above: '6'
      for:
        minutes: 10
    condition: []
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washingmachine_status
        option: "Running"

  - alias: Action - Set washing machine as finished
    trigger:
    - platform: numeric_state
      entity_id: sensor.washer_dryer_energy_monitor_watts
      below: '10'
      for:
        minutes: 7
    condition:
    - condition: state
      entity_id: input_select.washingmachine_status
      state: "Running"
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washingmachine_status
        option: "Finished"

# Finished, start notification loop, set status to off
  - alias: Notify - Washing machine finished
    trigger:
    - platform: state
      entity_id: input_select.washingmachine_status
      to: "Finished"
    action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.washingmachine_needs_emptying
    - service: homeassistant.turn_on
      entity_id: script.washer_dryer_needs_emptying_loop
    - service: input_select.select_option
      data:
        entity_id: input_select.washingmachine_status
        option: "Powered Off"

###################
## Washer dryer report status
##
  - alias: Emptied the washing machine
    trigger:
    - platform: state
      entity_id: input_boolean.washingmachine_status_enquiry
      to: "on"
    action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.washingmachine_needs_emptying
    - service: script.house_announce_diningroom
      data_template:
        tts_msg: "Washing machine status update acknowledged."

###################
## Triggers for iOS responses
##
  - alias: Washer dryer notification response 1
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHER_DRYER_EMPTYING_1
    action:
      - service: script.house_announce_diningroom
        data_template:
          tts_msg: "Okay, I'll remind you in ten minutes."
  # Flip the input_boolean, end the message loop
  - alias: Washer dryer notification response 2
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHER_DRYER_EMPTYING_2
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.washingmachine_needs_emptying
      - service: script.house_announce_diningroom
        data_template:
          tts_msg: "Okay, I'll stop reminding you."
