#
# binary_sensor.cube_158d0004212ae3  Fin cube
# binary_sensor.cube_158d0004212b1f  Jed cube
#
# Alert / Rotate / Double-tap / Flip 90 / Flip 180 / Free-fall / Shake /      Move / Swing
# On / brightness / 50% white / Next color / Prev color / colorloop / Off / 

    
input_select:
  cube_fin_light_color:
    name: Cube Fin light color
    options:
      - deeppink # 255,43,128   ## pink
      - magenta # 255,0,255 ## fuschia
      - red # 255,0,26 ## bright red
      - darkviolet # 147,0,211  ## dark violet 
      - royalblue # 0,191,255  ## deep sky blue
      - blue # 64,0,255  ## bright blue
      - deepskyblue # 71,209,204  ## turquoise
      - darkgreen # 0,99,0  ## dark green
      - gold # 255,200,48  ## yellowish
      - chocolate # 255,127,26  ## dark orange
  cube_jed_light_color:
    name: Cube Jed light color
    options:
      - deeppink # 255,43,128   ## pink
      - magenta # 255,0,255 ## fuschia
      - red # 255,0,26 ## bright red
      - darkviolet # 147,0,211  ## dark violet 
      - royalblue # 0,191,255  ## deep sky blue
      - blue # 64,0,255  ## bright blue
      - deepskyblue # 71,209,204  ## turquoise
      - darkgreen # 0,99,0  ## dark green
      - gold # 255,200,48  ## yellowish
      - chocolate # 255,127,26  ## dark orange

automation:
###################
# Fin's cube
#
# Alert
  # - alias: Cube Fin event alert
  #   trigger:
  #     platform: event
  #     event_type: xiaomi_aqara.cube_action
  #     event_data:
  #       entity_id: binary_sensor.cube_158d0004212ae3
  #       action_type: alert
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.fins_room
  #       data:
  #         effect: stop
  #         xy_color: [0.502, 0.414]
  #         brightness: 127
  #         transition: 1
# Flip 90
  - alias: Cube Fin event flip90
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212ae3
        action_type: flip90
    action:
      - service: input_select.select_next
        data:
          entity_id: input_select.cube_fin_light_color
      - service: light.turn_on
        entity_id: light.fins_room
        data_template:
          color_name: "{{ states('input_select.cube_fin_light_color') }}"
          brightness: 255
          effect: stop
# Flip 180
  - alias: Cube Fin event flip180
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212ae3
        action_type: flip180
    action:
      - service: input_select.select_previous
        data:
          entity_id: input_select.cube_fin_light_color
      - service: light.turn_on
        entity_id: light.fins_room
        data_template:
          color_name: "{{ states('input_select.cube_fin_light_color') }}"
          brightness: 255
          effect: stop
# Double tap
  - alias: Cube Fin event tap_twice
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212ae3
        action_type: tap_twice
    action:
      - service: light.turn_on
        entity_id: light.fins_room
        data:
          effect: stop
          xy_color: [0.502, 0.414]
          brightness: 127
          transition: 1
# Shake
  - alias: Cube Fin event shake_air
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212ae3
        action_type: shake_air
    action:
      - service: light.turn_on
        entity_id: light.fins_room
        data:
          effect: stop
      - service: light.turn_off
        entity_id: light.fins_room

# Free Fall
  - alias: Cube Fin event free_fall
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212ae3
        action_type: free_fall
    action:
      - service: light.turn_on
        entity_id: light.fins_room
        data:
          effect: colorloop
          brightness: 255

# Rotate
  - alias: Cube Fin rotate to set brightness
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212ae3
        action_type: rotate
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.fins_room
          brightness: >
            {%if trigger.event.data.action_value | float(0) > 0 %} 
              {%if states.light.fins_room.attributes.brightness < 206 %}
                {{ states.light.fins_room.attributes.brightness | int + 50 }}
              {% endif %}
            {% else %} 
              {%if states.light.fins_room.attributes.brightness > 49 %}
                {{ states.light.fins_room.attributes.brightness | int - 50 }}
              {% endif %}
            {% endif %}

###################
# Jed's cube
#
# Alert
  # - alias: Cube Jed event alert
  #   trigger:
  #     platform: event
  #     event_type: xiaomi_aqara.cube_action
  #     event_data:
  #       entity_id: binary_sensor.cube_158d0004212b1f
  #       action_type: alert
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.jeds_room
  #       data:
  #         effect: stop
  #         xy_color: [0.502, 0.414]
  #         brightness: 127
  #         transition: 1
# Flip 90
  - alias: Cube Jed event flip90
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212b1f
        action_type: flip90
    action:
      - service: input_select.select_next
        data:
          entity_id: input_select.cube_jed_light_color
      - service: light.turn_on
        entity_id: light.jeds_room
        data_template:
          color_name: "{{ states('input_select.cube_jed_light_color') }}"
          brightness: 255
          effect: stop
# Flip 180
  - alias: Cube Jed event flip180
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212b1f
        action_type: flip180
    action:
      - service: input_select.select_previous
        data:
          entity_id: input_select.cube_jed_light_color
      - service: light.turn_on
        entity_id: light.jeds_room
        data_template:
          color_name: "{{ states('input_select.cube_jed_light_color') }}"
          brightness: 255
          effect: stop
# Double tap
  - alias: Cube Jed event tap_twice
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212b1f
        action_type: tap_twice
    action:
      - service: light.turn_on
        entity_id: light.jeds_room
        data:
          effect: stop
          xy_color: [0.502, 0.414]
          brightness: 127
          transition: 1
# Shake
  - alias: Cube Jed event shake_air
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212b1f
        action_type: shake_air
    action:
      - service: light.turn_on
        entity_id: light.jeds_room
        data:
          effect: stop
      - service: light.turn_off
        entity_id: light.jeds_room

# Free Fall
  - alias: Cube Jed event free_fall
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212b1f
        action_type: free_fall
    action:
      - service: light.turn_on
        entity_id: light.jeds_room
        data:
          effect: colorloop
          brightness: 255

# Rotate
  - alias: Cube Jed rotate to set brightness
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0004212b1f
        action_type: rotate
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.jeds_room
          brightness: >
            {%if trigger.event.data.action_value | float(0) > 0 %} 
              {%if states.light.jeds_room.attributes.brightness < 206 %}
                {{ states.light.jeds_room.attributes.brightness | int + 50 }}
              {% endif %}
            {% else %} 
              {%if states.light.jeds_room.attributes.brightness > 49 %}
                {{ states.light.jeds_room.attributes.brightness | int - 50 }}
              {% endif %}
            {% endif %}